### ISSUE TITLE
hashes aren't equal for mongodb-linux-x86_64-ubuntu1604-latest

### ISSUE THREAD

**Issue by dimitriylol** [nodkz/mongodb-memory-server#113]
It's not the issue of mongodb-memory-server package but I don't know where to write. Maybe @nodkz will give some suggestion.

md5-file package which is used in mongodb-memory-server package produces the hash which is different from mongodb-linux-x86_64-ubuntu1604-latest.tgz.md5.

Steps to reproduce:
1. curl https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-latest.tgz > mongodb-linux-x86_64-ubuntu1604-latest.tgz
2. execute function from 'md5-file' package:
require('md5-file')('mongodb-linux-x86_64-ubuntu1604-latest.tgz', (err, hash) => { console.log('hash', hash) })
output:
hash f226069c34b1eeec18b8f5df042341e5
3. curl https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-latest.tgz.md5
output:
531fdef70d6f44770f68e168fb3f8e56  mongodb-linux-x86_64-ubuntu1604-latest.tgz

Any suggestions are welcomed

**Comment by manodupont** [comment]
Samething here!.

When trying to launch from inside my docker,

```
2018-12-07T15:13:45.169Z Mongo[34619] Starting MongoDB instance with following options: {"port":34619,"dbName":"jest","uri":"mongodb://127.0.0.1:34619/jest","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-448DsSq3f8Qmt91"}
2018-12-07T15:13:45.173Z Mongo[34619] MongoBinary options: {"downloadDir":"/opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"3.2.18"}
2018-12-07T15:13:45.262Z Mongo[34619] Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.2.18.tgz
2018-12-07T15:13:45.321Z Mongo[34619] renamed /opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-3.2.18.tgz.downloading to /opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-3.2.18.tgz
2018-12-07T15:13:45.322Z Mongo[34619] Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.2.18.tgz.md5
2018-12-07T15:13:45.355Z Mongo[34619] renamed /opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-3.2.18.tgz.md5.downloading to /opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-3.2.18.tgz.md5
Error: MongoBinaryDownload: md5 check is failed
    at /opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:150:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:28:103)
    at _next (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:30:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! Test failed.  See above for more details.
Downloading MongoDB 3.2.18: NaN % (0mb / NaNmb)
```

+1

**Comment by dimitriylol** [comment]
@manodupont if this behaviour depends on your environment, I'm not sure that this is the same issue. For making sure, you can remove node_modules (maybe you must remove this folder ~/.mongodb-binaries too) on your local machine and launch `npm i`. If you see the same message, then you're right, someone forgot to update md5 reference result. If not, then my best guess, that you have an issue with downloading files.

**Comment by manodupont** [comment]
Well its from my container. So everything should be freshly installed.! Ill test the latest build first .... thanks for the quick response.
