### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function on postinstall

### ISSUE THREAD

**Issue by Rolilink** [nodkz/mongodb-memory-server#118]
I am having an issue when installing the package on mac, it seems that there is a type error when the mongo binaries are downloaded.

```
Rolandos-MacBook-Pro:control rolilink$ npm install --save-dev mongodb-memory-server

> mongodb-memory-server@2.8.0 postinstall /Users/rolilink/Documents/Dev/nimbus9/core-orchestration/control/node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
events.js:180ongoDB latest: 99.8 % (66.8mb / 66.9mb)
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2302:10)
    at WriteStream.fileStream.on (/Users/rolilink/Documents/Dev/nimbus9/core-orchestration/control/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:245:24)
    at WriteStream.emit (events.js:164:20)
    at finishMaybe (_stream_writable.js:605:14)
    at afterWrite (_stream_writable.js:456:3)
    at onwrite (_stream_writable.js:446:7)
    at fs.js:2246:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)
npm WARN mongodb-memory-server@2.8.0 requires a peer of mongodb@>= 3.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongodb-memory-server@2.8.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mongodb-memory-server@2.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rolilink/.npm/_logs/2018-12-17T12_50_21_700Z-debug.log
```

**Comment by Rolilink** [comment]
Found the issue this is happening on `v9.3.0`, it seems my nvm was using a newer version of node instead of `lts/carbon`.

https://stackoverflow.com/questions/47962447/node-js-the-listener-argument-must-be-of-type-function?rq=1

changed node version and everything is working fine.

**Comment by hasezoey** [comment]
im using nodejs 12.14, and the current tests are nodejs 8 and nodejs 10, which all dont have this error, so i guess it is not required (even the typescript definition for it does not list any callback)
-> because of this i would close this issue
