### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by caub** [nodkz/mongodb-memory-server#140]
steps:

```sh
docker run --rm -it node:10-slim bash
# then in the container, run:
npm i mongodb mongodb-memory-server
node
# then in node repl:
const { MongoMemoryServer } = require('mongodb-memory-server');
mongoServer = new MongoMemoryServer({debug:true});
>   Mongo[35607] Starting MongoDB instance with following options: {"port":35607,"dbName":"5ceaba04-355b-4db9-a969-345f9e1f93d4","uri":"mongodb://127.0.0.1:35607/5ceaba04-355b-4db9-a969-345f9e1f93d4","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-26j6kUN3P9w2xk"} +0ms
(node:26) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1085:7)
    at /node_modules/mongodb-memory-server/lib/util/MongoBinary.js:134:204
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/node_modules/mongodb-memory-server/lib/util/MongoBinary.js:32:103)
    at _next (/node_modules/mongodb-memory-server/lib/util/MongoBinary.js:34:194)
    at /node_modules/mongodb-memory-server/lib/util/MongoBinary.js:34:364
    at new Promise (<anonymous>)
    at /node_modules/mongodb-memory-server/lib/util/MongoBinary.js:34:97
    at Function.getPath (/node_modules/mongodb-memory-server/lib/util/MongoBinary.js:195:7)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by caub** [comment]
or also

```
 docker run --rm -it node:slim bash
root@526360351d1a:/# npm i mongodb mongodb-memory-server

> mongodb-memory-server@3.1.1 postinstall /node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
failed to download/install MongoDB binaries. The error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object


```

**Comment by caub** [comment]
acutally, running `npm init -y` before the npm install, solve the problem

**Comment by AJRdev** [comment]
@caub Just to add some context the problem, you need to have a package.json in your repo otherwise the module find-cache-dir in MongoBinary.getPath() function will return null here : 
https://github.com/nodkz/mongodb-memory-server/blob/09723ce0454abbb5d8013df3e1b7b70acf1dc711/src/util/MongoBinary.js#L119

And the path.resolve will throw a TypeError ( path.resolve documentation : https://nodejs.org/api/path.html#path_path_resolve_paths )
The behaviour of find-cache-dir is indicated in its documentation as well : 

> findCacheDir([options])
> Finds the cache directory using the supplied options. The algorithm tries to find a package.json file, searching every parent directory of the cwd specified (or implied from other options). It returns a string containing the absolute path to the cache directory, or null if package.json was never found.
