### ISSUE TITLE
Topology was destroyed

### ISSUE THREAD

**Issue by sibelius** [nodkz/mongodb-memory-server#199]
mongoose: 5.6.0
mongodb-memory-server: 5.1.5

Sometimes I got this error:

```jsx
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
    MongoError: Topology was destroyed
        at initializeCursor (app/node_modules/mongodb-core/lib/cursor.js:596:25)
        at nextFunction (app/node_modules/mongodb-core/lib/cursor.js:456:12)
        at AggregationCursor.Object.<anonymous>.Cursor.next (app/node_modules/mongodb-core/lib/cursor.js:766:3)
        at AggregationCursor.Object.<anonymous>.Cursor._next (app/node_modules/mongodb/lib/cursor.js:216:36)
        at fetchDocs (app/node_modules/mongodb/lib/operations/cursor_ops.js:217:12)
        at toArray (app/node_modules/mongodb/lib/operations/cursor_ops.js:247:3)
        at executeOperation (app/node_modules/mongodb/lib/utils.js:416:24)
        at AggregationCursor.Object.<anonymous>.Cursor.toArray (app/node_modules/mongodb/lib/cursor.js:829:10)
        at collection.aggregate (app/node_modules/mongoose/lib/aggregate.js:969:16)
        at handleCallback (app/node_modules/mongodb/lib/utils.js:128:55)
        at aggregate (app/node_modules/mongodb/lib/operations/aggregate.js:116:10)
        at Collection.Object.<anonymous>.Collection.aggregate (app/node_modules/mongodb/lib/collection.js:1712:10)
        at NativeCollection.(anonymous function) [as aggregate] (app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:28)
        at model.hooks.execPre.error (app/node_modules/mongoose/lib/aggregate.js:959:18)
        at app/node_modules/kareem/index.js:23:7
        at process._tickCallback (internal/process/next_tick.js:61:11)
```

Anybody is having this errors?

This happens when we create a lot of fixtures (new User().save())
or when we do some aggregates

The following test is throwing when using this helper function (https://github.com/entria/debug-mongoose-aggregate)

```jsx
import { Model } from 'mongoose';
import util from 'util';

const debugWithMessage = (message = '', data: any) => {
  // tslint:disable-next-line
  console.log(message, util.inspect(data, false, null, true));
};

export const debugAggregate = async (model: Model, pipeline: any[]) => {
  for (let i=1; i<pipeline.length; i++) {
    const p = pipeline.slice(0, i);

    const result = await model.aggregate(p);

    debugWithMessage('Aggregation step:', p);
    debugWithMessage('Result:', result);
  }
};
```

**Comment by sibelius** [comment]
```jsx
MongoError: pool destroyed

      at Pool.Object.<anonymous>.Pool.write (node_modules/mongodb/lib/core/connection/pool.js:860:12)
      at _command (node_modules/mongodb/lib/core/wireprotocol/command.js:107:10)
      at command (node_modules/mongodb/lib/core/wireprotocol/command.js:25:5)
      at Object.query (node_modules/mongodb/lib/core/wireprotocol/query.js:57:3)
      at Server.Object.<anonymous>.Server.query (node_modules/mongodb/lib/core/topologies/server.js:640:16)
      at FindOperation.execute (node_modules/mongodb/lib/operations/find.js:24:12)
      at node_modules/mongodb/lib/operations/execute_operation.js:163:17
      at Server.Object.<anonymous>.Server.selectServer (node_modules/mongodb/lib/core/topologies/server.js:828:3)
      at Server.selectServer (node_modules/mongodb/lib/topologies/topology_base.js:363:32)
      at executeWithServerSelection (node_modules/mongodb/lib/operations/execute_operation.js:150:12)
      at executeOperation (node_modules/mongodb/lib/operations/execute_operation.js:81:16)
      at Cursor._initializeCursor (node_modules/mongodb/lib/core/cursor.js:545:7)
      at Cursor._initializeCursor (node_modules/mongodb/lib/cursor.js:191:11)
      at nextFunction (node_modules/mongodb/lib/core/cursor.js:748:10)
      at Cursor._next (node_modules/mongodb/lib/core/cursor.js:202:5)
      at nextObject (node_modules/mongodb/lib/operations/common_functions.js:235:10)
      at NextOperation.execute (node_modules/mongodb/lib/operations/next.js:26:5)
      at executeOperation (node_modules/mongodb/lib/operations/execute_operation.js:83:26)
      at Cursor.next (node_modules/mongodb/lib/cursor.js:217:12)
      at FindOneOperation.execute (node_modules/mongodb/lib/operations/find_one.js:26:12)
      at executeOperation (node_modules/mongodb/lib/operations/execute_operation.js:83:26)
      at Collection.<anonymous> (node_modules/mongodb/lib/collection.js:1026:12)
```

another error that happens for us in some tests

**Comment by sibelius** [comment]
MongoError: server instance pool was destroyed

**Comment by sibelius** [comment]
```jsx
MongoError: no connection available to server 127.0.0.1:52121
```

**Comment by khanguslee** [comment]
I'm also getting this issue when I run my Jest test. Looks like an issue with Mongoose and mongodb-memory-server?

**Comment by sibelius** [comment]
we kind of figure it out

if you have a collection with very nested fields, and you do findOne() without `lean:true`, it will be very slow

so it will hit the jest timeout (`jest.setTimeout(20000);`)

and it will close the conenction before finish the rest of operations

**Comment by sibelius** [comment]
this could happen if you forget a `await`
