### ISSUE TITLE
Cannot install package with npm

### ISSUE THREAD

**Issue by praveendath92** [nodkz/mongodb-memory-server#211]
I keep getting this error whenever I try to install

```
> mongodb-memory-server@5.1.10 postinstall /Users/praveen/Works/whos-in-bot/node_modules/mongodb-memory-server
> node ./postinstall.js

/Users/praveen/Works/whos-in-bot/node_modules/find-cache-dir/node_modules/find-up/index.js:29
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/praveen/Works/whos-in-bot/node_modules/find-cache-dir/node_modules/pkg-dir/index.js:3:16)
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none was installed.
npm ERR! Darwin 18.6.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mongodb-memory-server@5.1.10 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mongodb-memory-server@5.1.10 postinstall script 'node ./postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-memory-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongodb-memory-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongodb-memory-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/praveen/.npm/_logs/2019-08-03T01_47_49_348Z-debug.log
```

When I downgraded the version to `5.0.4`, it worked!

**Comment by hasezoey** [comment]
your nodejs version is too old, it dosnt support the `...` (rest parameters)
