### ISSUE TITLE
Permission Denied: When downloading OSX mongodb binaries

### ISSUE THREAD

**Issue by joseph-d-p** [nodkz/mongodb-memory-server#333]
## Versions

- NodeJS: 13.13.0
- mongodb-memory-server-*: ^6.6.4
- mongodb: ^3.5.6
- system: MacOS

package: mongo-memory-server 

## What is the Problem?

Unable to download OSX mongodb binaries when executing test.

<img width="983" alt="Screenshot 2020-08-18 at 8 28 49 AM" src="https://user-images.githubusercontent.com/16228946/90456488-a8335080-e12b-11ea-844a-56d4428fbdc0.png">

Debug log:

```
$ yarn test

Determining test suites to run...  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":53034,"dbName":"db-test","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"/var/folders/q3/n8nxnrp573gdr22nx_yz1lm80000gn/T/mongo-mem--74569-D46L7p4V0612","tmpDir":{"name":"/var/folders/q3/n8nxnrp573gdr22nx_yz1lm80000gn/T/mongo-mem--74569-D46L7p4V0612"},"uri":"mongodb://127.0.0.1:53034/db-test?"} +6ms
  MongoMS:MongoBinary MongoBinary options: {"downloadDir":"/Users/test/test-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"darwin","arch":"x64","version":"4.0.3","skipMD5":true} +0ms
  MongoMS:MongoBinaryDownloadUrl Using "mongodb-macos-x86_64-4.0.3.tgz" as the Archive String +0ms
  MongoMS:MongoBinaryDownloadUrl Using "https://fastdl.mongodb.org" as the mirror +1ms
  MongoMS:MongoBinaryDownload Downloading: "https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.0.3.tgz" +0ms
  MongoMS:MongoBinaryDownload trying to download https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.0.3.tgz +0ms
Error: Status Code is 403 (MongoDB's 404)

This means that the requested version-platform combination dosnt exist
    at ClientRequest.<anonymous> (/Users/test/test-server/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:381:44)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:472:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)

```

## Code Example

Error happened when running yarn test. Not even able to execute a test.

## Do you know *why* it happened?

*no*

**Comment by hasezoey** [comment]
`Access Denied` for mongodb's fastdownload means "the requested version does not exist"

**Comment by joseph-d-p** [comment]
Thanks @hasezoey.

Updated my `jest-mongodb-config` binary version.
