### ISSUE TITLE
TypeError: Invalid version latest

### ISSUE THREAD

**Issue by GabiOnea** [nodkz/mongodb-memory-server#345]
## Versions

- NodeJS: v12.18.2
- mongodb-memory-server-*: ^6.6.2
- mongodb: 4.2.8
- mongoose: 5.0.6
- system: Windows 10

package: mongo-memory-server 

## Code Example
Connection code:
```
var mongoServer = new MongoMemoryServer();
       dbUrl = await mongoServer.getUri();
      mongoose.connect(dbUrl, mongoogseConnectionOptions).then(() => {
        debug(`Connection to mongoDB on ${ dbUrl } established`);

        resolve();
      }).catch(error => {
        console.log(error);
        debug("Error connecting to ${ dbUrl }");
        debug('%O', error);

        debug('Retrying connection in %s seconds', retryTimeout / 1000);

        setTimeout(connectToMongo, retryTimeout);
      });
```
package.json:
```
 "config": {
    "mongodbMemoryServer": {
      "version": "latest"
    }
  },
```

Console output:
```
2020-08-28T11:34:19.265Z central-configuration-test:server Starting server.
2020-08-28T11:34:19.357Z central-configuration-test:server Listening on port: 2337
2020-08-28T11:34:19.464Z central-configuration-test:server TypeError: Invalid Version: latest
    at new SemVer (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\node_modules\semver\classes\semver.js:41:13)
    at compare (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\node_modules\semver\functions\gte.js:2:30)
    at MongoBinaryDownloadUrl.Object.<anonymous>.MongoBinaryDownloadUrl.translatePlatform (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\src\util\MongoBinaryDownloadUrl.ts:335:23)
    at new MongoBinaryDownloadUrl (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\src\util\MongoBinaryDownloadUrl.ts:27:26)
    at MongoBinaryDownload.<anonymous> (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\src\util\MongoBinaryDownload.ts:92:20)
    at step (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:56:23)
    at Object.next (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:37:53)
    at C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:31:71
    at new Promise (<anonymous>)
    at Object.<anonymous>.__awaiter (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:27:12)
    at MongoBinaryDownload.Object.<anonymous>.MongoBinaryDownload.startDownload (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:140:16)
    at MongoBinaryDownload.<anonymous> (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\src\util\MongoBinaryDownload.ts:76:39)
    at step (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:56:23)
    at Object.next (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:37:53)
    at fulfilled (C:\Users\Laptop\Documents\projects\central-configuration-be-ms\node_modules\mongodb-memory-server-core\lib\util\MongoBinaryDownload.js:28:58)
```

## Do you know *why* it happenes?

No.

**Comment by Vishal-vash** [comment]
Remove package-lock.json file, reinstall and run. 

This error goes away for me after following these steps.

**Comment by GabiOnea** [comment]
> Remove package-lock.json file, reinstall and run.
> 
> This error goes away for me after following these steps.

Tried it, same error.

**Comment by hasezoey** [comment]
are you sure you run version `6.6.2`? because `semver` was not used before 6.6.5 - please recheck your version of `mongo-memory-server`

**Comment by GabiOnea** [comment]
Hmm you were correct, due to the fact that mongodb-memory-server version was "^6.6.2" in package.json it was automatically downloaded as version 6.6.6 (checked in in package-lock.json). I've set the version in package.json to be 6..6.2 strict and the error is no longer showing up. Thanks!
