### ISSUE TITLE
SyntaxError: Invalid regular expression: /[\p{Ll}]/: Invalid escape

### ISSUE THREAD

**Issue by rvillane** [nodkz/mongodb-memory-server#379]
## Versions

- NodeJS: 10.12.0
- mongodb-memory-server-*: 6.7.6
- mongodb: 3.6.2
- mongoose: 5.10.5
- system: Linux Ubuntu

package: mongo-memory-server 

## What is the Problem?

getting this error when installing the latest version in Jenkins after upgrading from mongodb-memory-server@6.6.6 to mongodb-memory-server@6.7.6

```
> mongodb-memory-server@6.7.6 postinstall /home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server
> node ./postinstall.js

/home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server-core/node_modules/camelcase/index.js:17
} else if (isLastCharUpper && isLastLastCharUpper && /[\p{Ll}]/u.test(character)) {
^

SyntaxError: Invalid regular expression: /[\p{Ll}]/: Invalid escape
at preserveCamelCase (/home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server-core/node_modules/camelcase/index.js:17:33)
at Object.camelCase [as default] (/home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server-core/node_modules/camelcase/index.js:63:11)
at resolveConfig (/home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:43:217)
at Object. (/home/jenkins/workspace/etail-transaction-service_master/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:56:15)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongodb-memory-server@6.7.6 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1

```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
please upgrade your nodejs version, it is know that versions `>= 10.0.0 to <= 10.15.0` is brocken, so please upgrade to 10.15.0 (at least) and report back

**Comment by oldCoder29** [comment]
I still have this problem with latest version i.e mongodb-memory-server@6.9.0

Tried it on multiple node versions from 1v0.15.0 to  v14.13.0
OS : MacOs Catalina
still gives out same error : 
call stack : 
> mongodb-memory-server@6.9.0 postinstall /Users/me/some_prject/node_modules/mongodb-memory-server
> node ./postinstall.js

/Users/me/some_prject/node_modules/mongodb-memory-server-core/node_modules/camelcase/index.js:17
                } else if (isLastCharUpper && isLastLastCharUpper && /[\p{Ll}]/u.test(character)) {
                                              ^

SyntaxError: Invalid regular expression: /[\p{Ll}]/: Invalid escape
    at preserveCamelCase (/Users/me/some_prject/node_modules/mongodb-memory-server-core/node_modules/camelcase/index.js:17:33)
    at Object.camelCase [as default] (/Users/me/some_prject/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:43:217)
    at Object.<anonymous> (/Users/me/some_prject/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:56:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongodb-memory-server@6.9.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mongodb-memory-server@6.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-10-07T17_49_07_775Z-debug.log

**Comment by hasezoey** [comment]
@oldCoder29 are you sure you used nodejs above 10.15?

**Comment by oldCoder29** [comment]
yeah, is used different versions, still have the same problem. earlier was on v8.11.3, upgraded to the latest and then to  v10.15.0, have this error stack in every version.

**Comment by oldCoder29** [comment]
It worked now. Thanks

**Comment by hasezoey** [comment]
@oldCoder29 can i know what changed?

**Comment by oldCoder29** [comment]
some problem with version only this works fine.
