### ISSUE TITLE
Test using mongodb-memory-server is failing/timing out

### ISSUE THREAD

**Issue by andylebo20** [nodkz/mongodb-memory-server#421]
I’m setting up mongodb-memory-server in my backend for test purposes and am experiencing some issues when running tests that I am hoping someone could help me debug. My issue is that when I run my test (which will create a mongodb doc somewhere in the service being tested), the test times out. As I understand it, this is because when the test is executed and a new mongo doc is trying to be created during the test, I console log mongoose.connection.readyState and it says it’s 0, meaning that mongoose is disconnected. This is strange to me because I added console logs to my connectMongoose() function (pictured below) and it says that mongoose is connected. So my main question is why does it say mongoose is connected at the end of connectMongoose(), but it says it’s disconnected during the execution of the unit test/service function? How can I ensure that MongoDB-memory-server is fully connected prior to test execution?

Below is a screenshot showing how I am doing the mongoose test connection.
<img width="558" alt="Screen Shot 2020-11-26 at 3 10 26 PM" src="https://user-images.githubusercontent.com/62567315/100388764-85052080-2ff9-11eb-8788-0f057d7728e8.png">

Below this is a screenshot of exactly where and how mongodb-memory-server is being used
<img width="716" alt="Screen Shot 2020-11-26 at 3 11 09 PM" src="https://user-images.githubusercontent.com/62567315/100388800-9fd79500-2ff9-11eb-8acc-1a36f13fcad0.png">

Here is a screenshot of my jest.config.js:
<img width="556" alt="Screen Shot 2020-11-26 at 3 11 32 PM" src="https://user-images.githubusercontent.com/62567315/100388813-acf48400-2ff9-11eb-8822-a6236ad34777.png">

And finally the actual test file which has the failing test (what I’m asking about):
<img width="641" alt="Screen Shot 2020-11-26 at 3 11 51 PM" src="https://user-images.githubusercontent.com/62567315/100388829-b8e04600-2ff9-11eb-989c-2e83ca4317e5.png">

Please let me know if anyone needs any further clarification or screenshots, etc. Thank you so much in advance for your help!

**Comment by hasezoey** [comment]
sorry for an delayed response

---

where in the test provided is an new document created and saved to the database? (sorry im not familiar with `axios`)

**Comment by andylebo20** [comment]
@hasezoey no worries, here is the code in the service where the doc is attempted to get created:
```
import { User } from "../models/User";
import mongoose from "mongoose"

export class UserService {
  static async createUser(userBody) {
    return User.create(userBody);
  }
}
```
Note that this code works when attached to a real remote mongo database (just not the in-memory db)

**Comment by hasezoey** [comment]
from what i can see, there is not really an visible problem, from maybe aside that for each test file an new mongod server is started

maybe try to setup the server in `globalSetup` and stop it in `globalTeardown`, if you need an example, look at how typegoose does this:
- [jest config](https://github.com/typegoose/typegoose/blob/39e5d0c2050b500bc3255438cf8fefa44c652b13/jest.config.json#L28-L33)
- [global Setup](https://github.com/typegoose/typegoose/blob/39e5d0c2050b500bc3255438cf8fefa44c652b13/test/globalSetup.ts#L6-L21)
- [global Teardown](https://github.com/typegoose/typegoose/blob/39e5d0c2050b500bc3255438cf8fefa44c652b13/test/globalTeardown.ts#L4-L9)
- [setup file](https://github.com/typegoose/typegoose/blob/39e5d0c2050b500bc3255438cf8fefa44c652b13/test/setupFile.ts#L3-L9)

Note: `globalSetup` gets called *once* before any test suite runs, then `setupFilesAfterEnv` get run *once* in every test suite (and as the name says run after the environment (like NodeEnvrionment) gets called), then `globalTeardown` gets called *once* after all test suites have run (either successfully or failed)

---

if this still not works, could you also provide [debug output](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode) and/or test if an 7.0 version works (which is still in development)

**Comment by andylebo20** [comment]
@hasezoey thanks for your help! So I tried your suggestion as well as replicating the mongo testing code from the typegoose repo, but through both ways I am experiencing the same issue. I also tried console logging `mongoose.connection.readyState` right before I execute a mongo db function inside part of the service being tested, and that logs `0`, meaning that there is no db connection.

I just ran the tests again with debug on and received this output:
```
Determining test suites to run...  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method +0ms
  MongoMS:MongoMemoryServer  - no running instance, call `start()` command +0ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer starting with port 61207, since undefined was locked: 61207 +3ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":61207,"dbName":"ff74fbda-8d5b-489a-a61f-2a187d05e32f","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"/var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8","tmpDir":{"name":"/var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8"},"uri":"mongodb://127.0.0.1:61207/ff74fbda-8d5b-489a-a61f-2a187d05e32f?"} +1ms
  MongoMS:MongoBinary MongoBinary options: {
  "downloadDir": "/Users/andylebowitz/trading-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries",
  "platform": "darwin",
  "arch": "x64",
  "version": "4.0.14",
  "checkMD5": false
} +0ms
  MongoMS:MongoBinary MongoBinary: Download lock removed +2ms
  MongoMS:MongoBinary MongoBinary: Mongod binary path: "/Users/andylebowitz/trading-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod" +1ms
  MongoMS:MongoInstance Mongo[61207]: Called MongoInstance._launchKiller(parent: 67749, child: 67753): +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.246-0500 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
  MongoMS:MongoInstance  +21ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] MongoDB starting : pid=67753 port=61207 dbpath=/var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8 64-bit host=Andys-MBP
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] db version v4.0.14
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] git version: 1622021384533dade8b3c89ed3ecd80e1142c132
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] allocator: system
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] modules: none
  MongoMS:MongoInstance  +7ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] build environment:
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten]     distarch: x86_64
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten]     target_arch: x86_64
  MongoMS:MongoInstance 2020-12-07T21:15:28.254-0500 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 61207 }, security: { authorization: "disabled" }, storage: { dbPath: "/var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8", engine: "ephemeralForTest" } }
  MongoMS:MongoInstance  +1ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.256-0500 I CONTROL  [initandlisten]
  MongoMS:MongoInstance 2020-12-07T21:15:28.256-0500 I CONTROL  [initandlisten] ** NOTE: The ephemeralForTest storage engine is for testing only.
  MongoMS:MongoInstance 2020-12-07T21:15:28.256-0500 I CONTROL  [initandlisten] **       Do not use in production.
  MongoMS:MongoInstance 2020-12-07T21:15:28.256-0500 I CONTROL  [initandlisten]
  MongoMS:MongoInstance  +1ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.256-0500 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 4ae15beb-a46c-47fd-92e0-0c2ac85569ca
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.257-0500 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
  MongoMS:MongoInstance  +1ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.257-0500 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: db47dc78-f23b-449d-bb4b-e5af7117fde2
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.257-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8/diagnostic.data'
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.258-0500 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
  MongoMS:MongoInstance 2020-12-07T21:15:28.258-0500 I NETWORK  [initandlisten] waiting for connections on port 61207
  MongoMS:MongoInstance  +1ms
  MongoMS:MongoInstance Mongo[61207]: MongodbInstance: Instance is ready! +0ms
  MongoMS:MongoMemoryServer  - `start()` command was succesfully resolved +42ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.258-0500 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 33af304d-39a2-40d3-b304-6b33231bfb10
  MongoMS:MongoInstance 2020-12-07T21:15:28.259-0500 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
  MongoMS:MongoInstance 2020-12-07T21:15:28.259-0500 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
  MongoMS:MongoInstance 2020-12-07T21:15:28.259-0500 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
  MongoMS:MongoInstance  +11ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.269-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61208 #1 (1 connection now open)
  MongoMS:MongoInstance  +4ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.273-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:61208 conn1: { driver: { name: "nodejs|Mongoose", version: "3.6.3" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.6.0" }, platform: "'Node.js v14.5.0, LE (unified)", version: "3.6.3|5.11.5" }
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.279-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61209 #2 (2 connections now open)
  MongoMS:MongoInstance  +7ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.280-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:61209 conn2: { driver: { name: "nodejs|Mongoose", version: "3.6.3" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.6.0" }, platform: "'Node.js v14.5.0, LE (unified)", version: "3.6.3|5.11.5" }
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:28.284-0500 I NETWORK  [conn1] end connection 127.0.0.1:61208 (1 connection now open)
  MongoMS:MongoInstance 2020-12-07T21:15:28.285-0500 I NETWORK  [conn2] end connection 127.0.0.1:61209 (0 connections now open)
  MongoMS:MongoInstance  +5ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:29.622-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:61210 #3 (1 connection now open)
  MongoMS:MongoInstance  +1s
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:29.625-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:61210 conn3: { driver: { name: "nodejs|Mongoose", version: "3.6.3" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.6.0" }, platform: "'Node.js v14.5.0, LE (unified)", version: "3.6.3|5.11.5" }
  MongoMS:MongoInstance  +3ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.638-0500 I NETWORK  [conn3] end connection 127.0.0.1:61210 (0 connections now open)
  MongoMS:MongoInstance  +5s
 FAIL  src/tests/users.test.ts (6.317 s)
  Users
    ✕ creates a new user (5008 ms)

  ● Users › creates a new user

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

       6 |
       7 | describe("Users", () => {
    >  8 |   it("creates a new user", async () => {
         |   ^
       9 |     const userObj = {
      10 |       firstName: faker.name.firstName(),
      11 |       lastName: faker.name.lastName(),

      at new Spec (node_modules/jest/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/tests/users.test.ts:8:3)
      at Object.<anonymous> (src/tests/users.test.ts:7:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.362 s, estimated 7 s
Ran all test suites.
  MongoMS:MongoMemoryServer Called MongoMemoryServer.stop() method +6s
  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method +0ms
  MongoMS:MongoMemoryServer Shutdown MongoDB server on port 61207 with pid 67753 +0ms
  MongoMS:MongoInstance Mongo[61207]: Called MongoInstance.kill(): +24ms
  MongoMS:MongoInstance Mongo[61207]: - childProcess: send "SIGINT" +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.663-0500 I CONTROL  [signalProcessingThread] got signal 2 (Interrupt: 2), will terminate after current cmd ends
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.663-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
  MongoMS:MongoInstance 2020-12-07T21:15:34.663-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-61207.sock
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.663-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.663-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
  MongoMS:MongoInstance  +1ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.664-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: STDOUT: 2020-12-07T21:15:34.664-0500 I CONTROL  [signalProcessingThread] now exiting
  MongoMS:MongoInstance 2020-12-07T21:15:34.664-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
  MongoMS:MongoInstance  +0ms
  MongoMS:MongoInstance Mongo[61207]: - childProcess: got exit signal, Code: 0, Signal: null +2ms
  MongoMS:MongoInstance Mongo[61207]: - killerProcess: send "SIGINT" +0ms
  MongoMS:MongoInstance Mongo[61207]: CLOSE: 0 +1ms
  MongoMS:MongoInstance Mongo[61207]: MongodbInstance: Instance has failed: Mongod instance closed with code "0" +0ms
  MongoMS:MongoInstance Mongo[61207]: [MongoKiller]: exit - [null,"SIGTERM"] +2ms
  MongoMS:MongoInstance Mongo[61207]: - killerProcess: got exit signal, Code: null, Signal: SIGTERM +0ms
  MongoMS:MongoInstance Mongo[61207]: Instance Finished Shutdown +0ms
  MongoMS:MongoMemoryServer Removing tmpDir /var/folders/_r/mh0pdy8s6719zt__w0tgqzcm0000gn/T/mongo-mem--67749-UjT3wKYqdxF8 +7ms
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:67749) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Request failed with status code 500
(Use `node --trace-warnings ...` to show where the warning was created)
(node:67749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trading-server@1.0.0 test: `jest --passWithNoTests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trading-server@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andylebowitz/.npm/_logs/2020-12-08T02_15_39_690Z-debug.log
0587411940:trading-server andylebowitz$
```

**Comment by hasezoey** [comment]
based on the output given, i dont see an problem - could you make an reproduction repository (with tsconfig, package.json and executeable jest test(s))?

**Comment by andylebo20** [comment]
@hasezoey yep! here is a link to the repo: [https://github.com/andylebo20/trading-server-repro](https://github.com/andylebo20/trading-server-repro)

**Comment by hasezoey** [comment]
sorry, i tried your repo, but aside that your express server never gets started and the test tries to use it, there is no problem with the connection

even after fixing that the express server is not started, it works, i modified:
```ts
// index.ts
export const server = app.listen(port, () => {
  console.log(`💪 Server is running on port: ${port}`);
});

// users.test.ts
// added the import
import {server} from '../index';

// and an hook to close the server (otherwise jest open handle infinite running)
afterAll(() => {
  server.close();
})
```

**Comment by andylebo20** [comment]
@hasezoey ahhhh it seems my issue was that i kept another shell open to run the server at the same time (im used to doing that with other repos). thanks!

**Comment by Saucynet183** [comment]
@hasezoey https://pythondev.space/questions/mongodbs-sluggish-performance-leading-to-app-failures

**Comment by hasezoey** [comment]
@Saucynet183 I dont see how that link is related to this issue, could you explain?
To my understanding that link's issue is that it does a complete `collection.find()` (whole collection), which is not the case (or similar) for this issue.
