### ISSUE TITLE
Debian 10 missing "CURL_OPENSSL_3" library

### ISSUE THREAD

**Issue by netogerbi** [nodkz/mongodb-memory-server#476]
## Versions

- NodeJS: 12.18.3
- mongodb-memory-server-*: 6.9.6
- mongodb: 4.0.14
- mongoose: 5.10.19
- system: Linux (10 Buster)

package: mongo-memory-server

## What is the Problem?

MongoMemoryServer - thrown: "Mongod instance closed with code \"1\""

## Code Example

```ts
import { MongoMemoryServer } from "mongodb-memory-server";
import mongoose from "mongoose";

let mongo: any;
beforeAll(async () => {
  process.env.JWT_KEY = "asdfasdf";

  mongo = new MongoMemoryServer();
  const mongoUri = await mongo.getUri();

  await mongoose.connect(mongoUri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
});
```

```
  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method +0ms
  MongoMS:MongoMemoryServer  - no running instance, call `start()` command +1ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer starting with port 37377, since undefined was locked: 37377 +2ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":37377,"dbName":"1efc9b0e-8c6d-4f67-a0cf-c69b4419e6d2","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem--1420087-amzGusAdFL6J","tmpDir":{"name":"/tmp/mongo-mem--1420087-amzGusAdFL6J"},"uri":"mongodb://127.0.0.1:37377/1efc9b0e-8c6d-4f67-a0cf-c69b4419e6d2?"} +2ms
  MongoMS:MongoBinary MongoBinary options: {
  "downloadDir": "/home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries",
  "platform": "linux",
  "arch": "x64",
  "version": "4.0.14",
  "checkMD5": false
} +0ms
  MongoMS:getos Trying LSB-Release +0ms
  MongoMS:MongoBinaryDownloadUrl getDebianVersionString: requested version "4.0.14" not available for osrelease "10", using "92" +0ms
  MongoMS:MongoBinaryDownloadUrl Using "mongodb-linux-x86_64-debian92-4.0.14.tgz" as the Archive String +0ms
  MongoMS:MongoBinaryDownloadUrl Using "https://fastdl.mongodb.org" as the mirror +0ms
  MongoMS:MongoBinaryDownload Downloading: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.0.14.tgz" +0ms
  MongoMS:MongoBinaryDownload trying to download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.0.14.tgz +1ms
  MongoMS:MongoBinaryDownload moved /home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-4.0.14.tgz.downloading to /home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-4.0.14.tgz +10s
  MongoMS:MongoBinaryDownload extract(): /home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14 +1ms
  MongoMS:MongoBinary MongoBinary: Download lock removed +11s
  MongoMS:MongoBinary MongoBinary: Mongod binary path: "/home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod" +1ms
  MongoMS:MongoInstance Mongo[37377]: Called MongoInstance._launchKiller(parent: 1420087, child: 1420207): +0ms
  MongoMS:MongoInstance Mongo[37377]: STDERR: /home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/neto/workspace/Learning/ticketing/auth/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod)
  MongoMS:MongoInstance  +24ms
  MongoMS:MongoInstance Mongo[37377]: Mongod instance closed with an non-0 code! +0ms
  MongoMS:MongoInstance Mongo[37377]: CLOSE: 1 +1ms
  MongoMS:MongoInstance Mongo[37377]: MongodbInstance: Instance has failed: Mongod instance closed with code "1" +0ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.stop() method +11s
  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method +0ms
  MongoMS:MongoInstance Mongo[37377]: [MongoKiller]: exit - [null,"SIGTERM"] +41ms
```

I'v already tried to set the config below:

```
"mongodbMemoryServer": {
      "version": "latest"
}
```

it returns the following error:

```
TypeError: Invalid Version: latest

      at new SemVer (node_modules/mongodb-memory-server-core/node_modules/semver/classes/semver.js:38:13)
      at compare (node_modules/mongodb-memory-server-core/node_modules/semver/functions/compare.js:3:3)
      at Object.lte (node_modules/mongodb-memory-server-core/node_modules/semver/functions/lte.js:2:30)
      at MongoBinaryDownloadUrl.Object.<anonymous>.MongoBinaryDownloadUrl.getDebianVersionString (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:176:18)
      at MongoBinaryDownloadUrl.Object.<anonymous>.MongoBinaryDownloadUrl.getLinuxOSVersionString (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:146:19)
      at MongoBinaryDownloadUrl.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:119:23)
      at step (node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:52:23)
      at Object.next (node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:33:53)
      at fulfilled (node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:24:58)
```

I'm stucked on this issue... I'v found another issues like that but none resolved for me! I'm sorry if this issue is already resolved. If this is the case, please could anyone point the solution for me please!?

Thanks!

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
> I'v already tried to set the config below:

`latest` is not in all distros an valid option

---

your issue is that you have an mongodb binary which requires `CURL_OPENSSL_3`, if you already have version 4 installed, you should upgrade the mongodb version used (default for this version is `4.0.14`

---

PS: maybe try an `7.0.0-beta.x` version and see if an better version gets selected

**Comment by netogerbi** [comment]
@hasezoey You saved me, thank you very much! I configured the version to 4.4.6 that is the latest stable versionand it worked!
