### ISSUE TITLE
Download url format may be broken

### ISSUE THREAD

**Issue by Koleok** [nodkz/mongodb-memory-server#51]
Looks like the download url format may have changed and would need to be updated.

Recently when running tests I have been seeing the download fail for mongo binary, indeed if i follow the link _(in my case [3.6.0](https://downloads.mongodb.org/osx/mongodb-osx-x86_64-3.6.0.tgz))_ logged for the download I am seeing a standard s3 empty page like:

![image](https://user-images.githubusercontent.com/10928312/36601165-67ba3f2e-1882-11e8-9ed6-31ed45eba274.png)

Log output is as follows using this package with `{ debug: true }`:

```shell
Mongo[58989] Starting MongoDB instance with following options: {"port":58989,"dbName":"01d7602e-c235-4d6b-9009-db9f21c189f0","uri":"mongodb://localhost:58989/01d7602e-c235-4d6b-9009-db9f21c189f0","storageEngine":"ephemeralForTest","dbPath":"/var/folders/q2/5tmxbvwj6gs33d926p9_m45h0000gn/T/mongo-mem-51484gWf8ctpeqK84"} +0ms
  console.warn node_modules/node-uuid/uuid.js:48
    [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()

  console.log node_modules/mongodb-memory-server/lib/MongoMemoryServer.js:99
    Autostarting MongoDB instance...

  console.log node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:172
    Downloading MongoDB: https://downloads.mongodb.org/osx/mongodb-osx-x86_64-3.6.0.tgz

  Mongo[58989] renamed ~/.mongodb-binaries/mongodb-osx-x86_64-3.6.0.tgz.downloading to ~/.mongodb-binaries/mongodb-osx-x86_64-3.6.0.tgz +8s
  Mongo[59099] Starting MongoDB instance with following options: {"port":59099,"dbName":"e10683f2-87ed-4816-9320-2843d1c6fe35","uri":"mongodb://localhost:59099/e10683f2-87ed-4816-9320-2843d1c6fe35","storageEngine":"ephemeralForTest","dbPath":"/var/folders/q2/5tmxbvwj6gs33d926p9_m45h0000gn/T/mongo-mem-514841O3FXUa6dBXX"} +0ms
  console.log node_modules/mongodb-memory-server/lib/MongoMemoryServer.js:99
    Autostarting MongoDB instance...

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:198
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:199
    StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C341FADDCC53868E</RequestId><HostId>rOpZu2a1arUiUY5MRo2eFY3ZGLNWps9d6aYWhEtvTWYUUpJQLO3rdPRKc3s3Ny3jXoEUQA40+9Y=</HostId></Error>"
        at new StatusCodeError (~/myProject/node_modules/request-promise-core/lib/errors.js:32:15)
        at Request.plumbing.callback (~/myProject/node_modules/request-promise-core/lib/plumbing.js:104:33)
        at Request.RP$callback [as _callback] (~/myProject/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at Request.self.callback (~/myProject/node_modules/request/request.js:186:22)
        at Request.emit (events.js:125:13)
        at Request.emit (domain.js:421:20)
        at Request.<anonymous> (~/myProject/node_modules/request/request.js:1163:10)
        at Request.emit (events.js:125:13)
        at Request.emit (domain.js:421:20)
        at IncomingMessage.<anonymous> (~/myProject/node_modules/request/request.js:1085:12)
        at Object.onceWrapper (events.js:217:13)
        at IncomingMessage.emit (events.js:130:15)
        at IncomingMessage.emit (domain.js:421:20)
        at endReadableNT (_stream_readable.js:1101:12)
        at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by Koleok** [comment]
Also seems that even if i manually download the correct mongo binary and rename it to match the name given by `mongodb-memory-server`, the download is still attempted, which doesn't line up with the following statement describing this behavior in the readme:
> This package on first start downloads the latest MongoDB binaries and save it to ~/.mongodb-binaries folder. So first run may take a time. All further runs will fast, because use already downloaded binaries.

**Comment by nodkz** [comment]
For 3.6.0 try following option `binary.ssl=true`


From readme:
ssl?: boolean, // by default false (use it if mongodb dist has only ssl version binary)

Feel free to send PR if you have any additions or brings clearence to docs ;)

**Comment by Koleok** [comment]
@nodkz thanks I'll give it a try 👍

**Comment by Koleok** [comment]
yep worked like a charm, thanks for the tip sir 😀
