### ISSUE TITLE
Custom version results in "spawn UNKNOWN" for each test

### ISSUE THREAD

**Issue by Hampfh** [nodkz/mongodb-memory-server#557]
## Versions

- NodeJS: 16.11.1
- mongodb-memory-server: ^7.4.4
- mongoose: 6.0.10
- jest: ^27.2.5
- system: Windows

package: mongo-memory-server

## What is your question?
First of all I just want to clarify that this happened out of the blue, my integration worked flawlessly last time I ran the test suite (however this was a while ago, maybe a few months ago). The problem I have is that every time I initialize a test I get a `spawn UNKNOWN` error when trying to instantiate the memory server. This happens ONLY when I use a custom version (I've tried multiple versions but for this issue, I use mongo version 4.2.8) of MongoDB. When not applying any env variables the server instantiates properly (however I get other errors related to me using code that isn't supported by versions lower than 4.2 but this is expected since the default binary is 4.0.25 from my understanding). Where is this error coming from and why can I not assign a custom version? I've tried to specify multiple versions and download URLs. Currently the download_url uses the ubuntu-package because this was given as an example in the docs but I've tried for windows too with no other result.
  
  
The important parts of my code is:
(.env)
```env
MONGOMS_DEBUG=1
MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.2.8.tgz
MONGOMS_VERSION=4.2.8
```
(db.test.ts)
```typescript
import { MongoMemoryServer } from "mongodb-memory-server"
import mongoose from "mongoose"

// Set ES6 promises to mongoose default
require("mongoose").Promise = global.Promise

jest.setTimeout(10000)

export async function mockDB(): Promise<void> {
	let memoryServer: MongoMemoryServer
	// Clear database before each test
	beforeEach(done => {
		if (mongoose.connection.db == null) {
			done()
			return
		}
		mongoose.connection.db.listCollections().toArray((err, collections) => {

			if (err) {
				console.warn("Error: ", err)
				done()
			}
			else if (collections != null) {
				const promises: Array<Promise<unknown>> = []
				for (let i = 0; i < collections.length; i++)
					promises.push(mongoose.connection.collections[collections[i].name].drop())

				Promise.all(promises)
					.then(() => done())
					.catch((err) => {
						console.warn("Error: ", err)
						done()
					})
			}
		})
	})

	// Memory database initializer
	beforeAll(async () => {
		memoryServer = await MongoMemoryServer.create()
		
		const uri = memoryServer.getUri()

		mongoose.connect(uri, {}, (err) => {
			if (err) console.error(err)
		})
	})
	// Memory database destructor
	afterAll(async () => {
		await mongoose.disconnect()
		await memoryServer?.stop()
	})
}
```

Here is by debug stack trace when performing `npx jest file.ts`:

```logs
MongoMS:ResolveConfig Debug Mode Enabled, through Environment Variable +0ms
MongoMS:ResolveConfig findPackageJson: Found package.json at "D:\Creations\Development\web\Project\Project-server\package.json" +1ms
MongoMS:ResolveConfig Debug Mode Enabled, through package.json +1ms
MongoMS:MongoMemoryServer create: Called .create() method +0ms
MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method +0ms
MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method +1ms
MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions +0ms
MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
instance: {
port: 58783,
dbName: '',
ip: '127.0.0.1',
storageEngine: 'ephemeralForTest',
replSet: undefined,
dbPath: 'C:\\Users\\<user>\\AppData\\Local\\Temp\\mongo-mem--24080-2T5R0GM8JWgv',
tmpDir: {
    name: 'C:\\Users\\<user>\\AppData\\Local\\Temp\\mongo-mem--24080-2T5R0GM8JWgv',
    removeCallback: [Function: _cleanupCallback]
},
args: undefined,
auth: undefined
},
binary: { version: '4.2.8' },
spawn: undefined
} +5ms
MongoMS:MongoInstance create: Called .create() method +0ms
MongoMS:MongoInstance Mongo[58783]: start +0ms
MongoMS:MongoBinary getPath +0ms
MongoMS:DryMongoBinary generateOptions +0ms
MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +2ms
MongoMS:DryMongoBinary generatePaths +0ms
MongoMS:DryMongoBinary getBinaryName +0ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary combineBinaryName +0ms
MongoMS:DryMongoBinary generateDownloadPath: Paths: {
legacyHomeCache: 'C:\\Users\\<user>\\.cache\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
modulesCache: 'D:\\Creations\\Development\\web\\Project\\Project-server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-4.2.8.exe',
relative: 'D:\\Creations\\Development\\web\\Project\\Project-server\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
resolveConfig: ''
}  +0ms
MongoMS:DryMongoBinary generateDownloadPath: Found binary in legacyHomeCache: "C:\Users\<user>\.cache\mongodb-binaries\mongod-x64-win32-4.2.8.exe" +6ms
MongoMS:MongoBinary getPath: MongoBinary options: {
"version": "4.2.8",
"downloadDir": "C:\\Users\\<user>\\.cache\\mongodb-binaries",
"os": {
"os": "win32"
},
"arch": "x64",
"systemBinary": "",
"platform": "win32",
"checkMD5": false
} +11ms
MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "4.2.8" +2ms
MongoMS:DryMongoBinary generateOptions +0ms
MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +0ms
MongoMS:DryMongoBinary generatePaths +1ms
MongoMS:DryMongoBinary getBinaryName +0ms
MongoMS:DryMongoBinary combineBinaryName +0ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +0ms
MongoMS:DryMongoBinary combineBinaryName +0ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary generateDownloadPath: Paths: {
legacyHomeCache: 'C:\\Users\\<user>\\.cache\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
modulesCache: 'D:\\Creations\\Development\\web\\Project\\Project-server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-4.2.8.exe',
relative: 'D:\\Creations\\Development\\web\\Project\\Project-server\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
resolveConfig: 'C:\\Users\\<user>\\.cache\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe'
}  +0ms
MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "C:\Users\<user>\.cache\mongodb-binaries\mongod-x64-win32-4.2.8.exe" +1ms
MongoMS:DryMongoBinary locateBinary: running generateDownloadPath +0ms
MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +1ms
MongoMS:DryMongoBinary generatePaths +0ms
MongoMS:DryMongoBinary getBinaryName +0ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary combineBinaryName +0ms
MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +0ms
MongoMS:DryMongoBinary combineBinaryName +1ms
MongoMS:DryMongoBinary combineBinaryName +0ms
MongoMS:DryMongoBinary generateDownloadPath: Paths: {
legacyHomeCache: 'C:\\Users\\<user>\\.cache\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
modulesCache: 'D:\\Creations\\Development\\web\\Project\\Project-server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-4.2.8.exe',
relative: 'D:\\Creations\\Development\\web\\Project\\Project-server\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe',
resolveConfig: 'C:\\Users\\<user>\\.cache\\mongodb-binaries\\mongod-x64-win32-4.2.8.exe'
}  +0ms
MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "C:\Users\<user>\.cache\mongodb-binaries\mongod-x64-win32-4.2.8.exe" +1ms
MongoMS:DryMongoBinary locateBinary: found binary at "C:\Users\<user>\.cache\mongodb-binaries\mongod-x64-win32-4.2.8.exe" +0ms  MongoMS:MongoBinary getPath: Mongod binary path: "C:\Users\<user>\.cache\mongodb-binaries\mongod-x64-win32-4.2.8.exe" +10ms   
MongoMS:MongoInstance Mongo[58783]: start: Starting Processes +22ms
MongoMS:MongoInstance Mongo[58783]: _launchMongod: Launching Mongod Process +1ms
MongoMS:MongoInstance Mongo[58783]: prepareCommandArgs +0ms
MongoMS:MongoInstance Mongo[58783]: prepareCommandArgs: final argument array:["--port","58783","--dbpath","C:\\Users\\<user>\\AppData\\Local\\Temp\\mongo-mem--24080-2T5R0GM8JWgv","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"] +0ms
FAIL  src/__tests__/meeting/meeting.test.ts
Meeting tests
× Create a meeting (1 ms)
× Gets a specific meeting
× Gets all meetings associated to the user
× Updates a meeting (no parameters)
× Updates a meeting title
× Updates a meeting description
× Delete a meeting (without specifying a token)
× Deletes a meeting

● Meeting tests › Create a meeting

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Gets a specific meeting

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Gets all meetings associated to the user

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Updates a meeting (no parameters)

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Updates a meeting title

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Updates a meeting description

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Delete a meeting (without specifying a token)

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)

● Meeting tests › Deletes a meeting

spawn UNKNOWN

    at MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:443:31)
    at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:345:31)
    at fulfilled (node_modules/tslib/tslib.js:114:62)
```

**Comment by hasezoey** [comment]
> I guess that there is some clash when you define the version both in the .env file and in the .create() function?:

 do you mean you have the version set as a option in `create` and as a environment variable?

**Comment by Hampfh** [comment]
Hi sorry if I was a bit unspecific, what I meant with a `clash` is that if I specified a version in the .env file **and** the `binary.version` then the expected behavior (which is that the `binary.version` will overwrite the .env value) didn't happen, instead I got some weird error telling me about some lock file etc... 

But it was an easy fix to just remove the binary definition and keep the environmental variable

**Comment by Hampfh** [comment]
Hi, no all errors are gone after I updated the url, cleared the cache and removed the binary version
