### ISSUE TITLE
Why MongoMemoryServer instance not starting properly when using with NestJs MongooseModule?

### ISSUE THREAD

**Issue by vanuverma** [nodkz/mongodb-memory-server#620]
## Versions

- NodeJS: 16.14.0
- NestJs-Core: 8.4.0
- NestJs-Mongoose: 9.0.3
- mongodb-memory-server: 8.4.0 
- mongodb(the binary version): 5.0.3
- mongodb(the js package): N/A (not using in code)
- mongoose: 6.2.4
- system: MacOS
- Typescript: 4.6.2

package: mongo-memory-server (v8.4.0)

## What is your question?

Q: Why MongoMemoryServer instance not starting properly when using with NestJs MongooseModule?

Below is my test block (simplified):
```
describe('IdentityUserInterceptor', () => {
    let module: TestingModule;
    let loginProvider: string;
    let app: NestApplication;
    let authToken: string;
    let userAccountRepository: UserAccountRepository;
    let userDeviceRepository: UserDeviceRepository;
    let identityUserRepository: IdentityUserRepository;
    let env: TestEnvironment;
    let rawDeviceId: string;
    let platformId: string;
    let syncIdentityWithUser: jest.SpyInstance;
    let syncDlUser: jest.SpyInstance;
    let syncUserDevice: jest.SpyInstance;
    let mongod: MongoMemoryServer;
    // let mongoose: any;

    

    beforeEach(async () => {
        
        try {
            mongod = await MongoMemoryServer.create({
                binary: {
                    version: '5.0.3',
                },
                instance: {
                    dbName: 'in-mem-db',
                    auth: false,
                },
            });
        } catch (err) {
            console.log(err);
        }

        env = new TestEnvironment();

        module = await env.compileModule({
            imports: [
                // other module imports here
                MongooseModule.forRootAsync({
                    useFactory: async () => ({
                        uri: mongod.getUri(),
                    })
                }),
            ],
            controllers: [TestController],
        });

        userAccountRepository = module.get(UserAccountRepository);
        userDeviceRepository = module.get(UserDeviceRepository);
        identityUserRepository = module.get(IdentityUserRepository);

        app = module.createNestApplication(undefined, {
            logger: LoggerFactory.getNestLogger(),
        });

        // some jest spy here

        await app.init();
    });

    afterEach(async () => {
        await app.close();
        // await mongoose.disconnect();
        await mongod.stop();
    })

    // afterAll(async () => {
    //     await MockMongooseModule.close();
    //     // await app.close();
    // });

    it('should not sync the user with IdentityUser, UserAccount, UserDevice, on identityUserRepository if there is no valid user', async () => {
        // jest.setTimeout(30000);
        authToken = await env.createCertToken();
        const response = await request(app.getHttpServer())
            .get('/cert-test')
            .set({
                [DEVICE_ID_HEADER]: rawDeviceId,
                [AUTH_BEARER_HEADER]: authToken,
                [PLATFORM_HEADER]: platformId,
            });

        console.log(response);
        
        expect(response.status).toBe(HttpStatus.OK);

        expect(syncIdentityWithUser).not.toBeCalled();
        expect(syncDlUser).not.toBeCalled();
        expect(syncUserDevice).not.toBeCalled();
    });
});
```
The output of the `console.log(err)` from `try...catch` block is below:
```
TypeError: Cannot read properties of undefined (reading 'stat')
        at /Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/mongodb-memory-server-core/src/util/utils.ts:190:21
        at Generator.next (<anonymous>)
        at /Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/tslib/tslib.js:117:75
        at new Promise (<anonymous>)
        at __awaiter (/Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/tslib/tslib.js:113:16)
        at statPath (/Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/mongodb-memory-server-core/lib/util/utils.js:156:34)
        at /Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/mongodb-memory-server-core/src/util/utils.ts:207:35
        at Generator.next (<anonymous>)
        at /Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/tslib/tslib.js:117:75
        at new Promise (<anonymous>)
```
Logs after enabling the `debug` mode are below:
```
MongoMS:ResolveConfig Debug Mode Enabled, through package.json +0ms
  MongoMS:MongoMemoryServer create: Called .create() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method +1ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions: forceSamePort: false +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
  instance: {
    port: 57177,
    dbName: 'in-mem-db',
    ip: '127.0.0.1',
    storageEngine: 'ephemeralForTest',
    replSet: undefined,
    dbPath: '/var/folders/m5/7zryh8ms2pv76wl3mhd1w4kw0000gp/T/mongo-mem--94658-eZl2Uxoq617p',
    tmpDir: {
      name: '/var/folders/m5/7zryh8ms2pv76wl3mhd1w4kw0000gp/T/mongo-mem--94658-eZl2Uxoq617p',
      removeCallback: [Function: _cleanupCallback]
    },
    args: undefined,
    auth: false
  },
  binary: { version: '5.0.3' },
  spawn: undefined
} +3ms
  MongoMS:MongoInstance create: Called .create() method +0ms
  MongoMS:MongoInstance Mongo[57177]: start +1ms
  MongoMS:MongoBinary getPath +0ms
  MongoMS:DryMongoBinary generateOptions +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +1ms
  MongoMS:DryMongoBinary generatePaths {
  version: '5.0.3',
  downloadDir: '',
  os: { os: 'darwin' },
  arch: 'x64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +1ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/Users/vanu.verma/.cache/mongodb-binaries/mongod-x64-darwin-5.0.3',
  modulesCache: '/Users/vanu.verma/PROJECTS/microservices-2/common-lib/node_modules/.cache/mongodb-memory-server/mongod-x64-darwin-5.0.3',
  relative: '/Users/vanu.verma/PROJECTS/microservices-2/common-lib/mongodb-binaries/mongod-x64-darwin-5.0.3',
  resolveConfig: ''
}  +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method +5ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?) +0ms
```

**Comment by hasezoey** [comment]
> TypeError: Cannot read properties of undefined (reading 'stat')

it seems like that `fs.promises` somehow does not exist when our function is called, possible reasons i can think of:
- you have it mocked and did not unmock or did not provide the proper functions
- ESM is used (i dont know if this would really affect anything)
- a transpiler / minification is used that somehow stripped it of its import
- a custom nodejs runtime is used that somehow does not provide the `fs.promises` api

**Comment by vanuverma** [comment]
Hi @hasezoey thank you, it's the `fs` mock that I had in my test file.

**Comment by hasezoey** [comment]
i have changed the title to match what the issue was in the end, also thanks for sharing what was the problem
