### ISSUE TITLE
Unknown system error -86

### ISSUE THREAD

**Issue by k2xl** [nodkz/mongodb-memory-server#674]
## Versions

- NodeJS: 18.5.0
- mongodb-memory-server-*: 8.5.2 
- mongodb(the binary version): 0 
- mongodb(the js package): 4.5.0 
- mongoose: 6.2.4 
- system: Mac Pro M1

package: mongo-memory-server 

## What is the Problem?

When starting on fresh Mac M1 I am getting this:
```
error - Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:692:9)
    at MongoInstance._launchMongod (/Users/dannymiller/code/pathology/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:225:56)
    at MongoInstance.<anonymous> (/Users/dannymiller/code/pathology/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:146:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dannymiller/code/pathology/node_modules/mongodb-memory-server-core/node_modules/tslib/tslib.js:115:62) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn',
  page: '/'
```

What is strange is that it worked before - but reading online that this issue sometimes happens with M1.

**Comment by hasezoey** [comment]
Error `-86` on a MacOS Arm System commonly means Rosetta (the translation engine / layer) is not installed or setup correctly

**Comment by k2xl** [comment]
Indeed it did fix it.

For anyone else landing on the thread. Quick way to install:
`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`

**Comment by hasezoey** [comment]
Closing because resolved
