### ISSUE TITLE
Cannot start mongodb-memory-server on company Gitlab-CI

### ISSUE THREAD

**Issue by jpilgrim** [nodkz/mongodb-memory-server#687]
## Versions

- NodeJS: 18
- mongodb-memory-server-*: 8.8.0
- system: gitlab-ci, see below

## What is your question?

I have a very simple project using mongoose. For testing, I use mongodb-memory-server. That is, in the package.json, I define the following dependencies (only the once related to mongodb):
```
"dependencies": {
    ...
    "mongoose": "^6.5.1"
  },
  "devDependencies": {
    "mongodb-memory-server": "^8.8.0",
    "ts-jest": "^28.0.7",
     "typescript": "^4.7.4"
  }
```

### It's woking locally

Locally (on macos/M1) it works (`npm install && npm test`).

### It's working locally in a docker container

I run the project in a docker container on a macos/Intel machine like that:
```
docker run -v /my/sampleApp:/sampleApp -it node:18 /bin/bash
root@c7478556a9cb:/# cd sampleApp/
root@c7478556a9cb:/sampleApp# npm install
...
root@c7478556a9cb:/sampleApp# npm test
...
```
The mongodb-memory-server is downloaded and launched successfully and all tests pass.
(Note that the docker container thing is not working on the macos/M1 machine, since mongod-arm64-debian-5.0.8 does not exists, but that's a different story).

### Gitlab-CI 

Now I want to run the very same tests on Gitlab-CI .

This is my gitlab-ci-yml:
```
image: node:18

stages:
  - test

javascript:
  stage: test
  script:
    - npm install
    - npm test
```

#### It's working on gitlab.com

It is working on gitlab.com.

#### It's not working on the company's gitlab instance.

Unfortunately it is not working on the company's gitlab instance. 

This is (part of) the log output:

```
Running with gitlab-runner 14.8.2 (c6e7e194)
  on gitlab-runner02-docker 36e0ade1
Preparing the "docker" executor
Using Docker executor with image node:18 ...
...
$ npm install
...
$ npm test
> sampleapp@1.0.0 test
> jest
 MongoMS:ResolveConfig Debug Mode Enabled, through package.json
 MongoMS:MongoMemoryServer create: Called .create() method
 MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method
 MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method
 MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions: forceSamePort: false
 MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
  instance: {
    port: 34219,
    dbName: '',
    ip: '127.0.0.1',
    storageEngine: 'ephemeralForTest',
    replSet: undefined,
    dbPath: '/tmp/mongo-mem--45-fD1btrl3PwaA',
    tmpDir: {
      name: '/tmp/mongo-mem--45-fD1btrl3PwaA',
      removeCallback: [Function: _cleanupCallback]
    },
    keyfileLocation: undefined,
    args: undefined,
    auth: false
  },
  binary: undefined,
  spawn: undefined
}
 MongoMS:MongoInstance create: Called .create() method
 MongoMS:MongoInstance Mongo[34219]: start
 MongoMS:MongoBinary getPath
 MongoMS:DryMongoBinary generateOptions
 MongoMS:utils tryReleaseFile: "/etc/upstream-release/lsb-release" does not exist
 MongoMS:getos getLinuxInformation: Using etcOsRelease
 MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
 MongoMS:DryMongoBinary generatePaths {
  version: '5.0.8',
  downloadDir: '',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'bullseye',
    release: '11',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
 MongoMS:DryMongoBinary getBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8',
  modulesCache: '/builds/we2-2022/playground/sampleApp/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.8',
  relative: '/builds/we2-2022/playground/sampleApp/mongodb-binaries/mongod-x64-debian-5.0.8',
  resolveConfig: ''
} 
 MongoMS:DryMongoBinary generateDownloadPath: Found binary in legacyHomeCache: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8"
 MongoMS:MongoBinary getPath: MongoBinary options: {
  "version": "5.0.8",
  "downloadDir": "/root/.cache/mongodb-binaries",
  "os": {
    "os": "linux",
    "dist": "debian",
    "codename": "bullseye",
    "release": "11"
  },
  "platform": "linux",
  "arch": "x64",
  "systemBinary": "",
  "checkMD5": false
}
 MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "5.0.8"
 MongoMS:DryMongoBinary generateOptions
 MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
 MongoMS:DryMongoBinary generatePaths {
  version: '5.0.8',
  downloadDir: '/root/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'bullseye',
    release: '11',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
 MongoMS:DryMongoBinary getBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8',
  modulesCache: '/builds/we2-2022/playground/sampleApp/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.8',
  relative: '/builds/we2-2022/playground/sampleApp/mongodb-binaries/mongod-x64-debian-5.0.8',
  resolveConfig: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8'
} 
 MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8"
 MongoMS:DryMongoBinary locateBinary: running generateDownloadPath
 MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
 MongoMS:DryMongoBinary generatePaths {
  version: '5.0.8',
  downloadDir: '/root/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'bullseye',
    release: '11',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
 MongoMS:DryMongoBinary getBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary combineBinaryName
 MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8',
  modulesCache: '/builds/we2-2022/playground/sampleApp/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.8',
  relative: '/builds/we2-2022/playground/sampleApp/mongodb-binaries/mongod-x64-debian-5.0.8',
  resolveConfig: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8'
} 
 MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8"
 MongoMS:DryMongoBinary locateBinary: found binary at "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8"
 MongoMS:MongoBinary getPath: Mongod binary path: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.8"
 MongoMS:MongoInstance Mongo[34219]: start: Starting Processes
 MongoMS:MongoInstance Mongo[34219]: _launchMongod: Launching Mongod Process
 MongoMS:MongoInstance Mongo[34219]: prepareCommandArgs
 MongoMS:MongoInstance Mongo[34219]: prepareCommandArgs: final argument array:["--port","34219","--dbpath","/tmp/mongo-mem--45-fD1btrl3PwaA","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"]
 MongoMS:MongoInstance Mongo[34219]: _launchKiller: Launching Killer Process (parent: 45, child: 64)
 MongoMS:MongoInstance Mongo[34219]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code!
 MongoMS:MongoInstance Mongo[34219]: closeHandler: code: "null", signal: "SIGILL"
 MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance threw a Error:  Error: Instance Exited before being ready and without throwing an error!
    at MongoInstance.<anonymous> (/builds/we2-2022/playground/sampleApp/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:338:13)
    at Object.onceWrapper (node:events:628:26)
    at MongoInstance.emit (node:events:513:28)
    at MongoInstance.closeHandler (/builds/we2-2022/playground/sampleApp/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:513:10)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
 MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method
...
ERROR: Job failed: exit code 1
```

So, everything looks fine, binary has been successfully downloaded and located, but then "Mongod instance closed with an non-0 (or non 12 on windows) code!".

What do I miss? I mean, it's inside a docker container... I have no idea what is blocking it in this special case?

This is how I start the server:
```
const mongo = await MongoMemoryServer.create();
const uri = mongo.getUri();
await mongoose.connect(uri);
```

Are there any arguments or tweaks I could apply?

**Comment by hasezoey** [comment]
the instance was spawned but almost immediately exited with `code: "null", signal: "SIGILL"`, which means "Illegal instruction", this means mongodb either tries to execute a invalid instruction (unlikely) or a privileged instruction, though no mention on what caused it

is your companies gitlab CI maybe modifying docker capabilities or maybe running a outdated gitlab-runner which has "misconfigured" capabilities?

**Comment by jpilgrim** [comment]
OK, I found a workaround: Use another MongoDB version.
I simply added the following lines to my package.json:

```
 "config": {
    "mongodbMemoryServer": {
      "version": "4.4.6"
    }
  }
```

Now it is working. Got the idea from [593#issuecomment-1032189179](593#issuecomment-1032189179): "does your CPU support AVX? (if not, try mongodb 4.x)"
