### ISSUE TITLE
Memory leak when just starting and stopping the server in jest test

### ISSUE THREAD

**Issue by BioSurienDG** [nodkz/mongodb-memory-server#713]
## Versions

- NodeJS: v14.18.1
- mongodb-memory-server-*: 8.9.5
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 4.4.0
- mongoose: 0.0.0 
- system: MacOS

package: mongo-memory-server 

## What is the Problem?

Whenever I start and stop the server I get a memory leak in my jest tests

## Code Example

```ts
describe('testing, () => {
    let memorySever: MongoMemoryServer;

    beforeAll(async () => {
        memorySever = new MongoMemoryServer();
        await memorySever.start();
    });
    afterAll(async () => {
        await memorySever.stop();
        memorySever = undefined;
    });
});
```

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (../../node_modules/@jest/core/build/TestScheduler.js:190:18)
      at ../../node_modules/@jest/core/build/TestScheduler.js:316:17
      at ../../node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (../../node_modules/emittery/index.js:258:23)
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
i dont know where memory is leaking, if possible could you be more specific? MMS caches some data between servers and that data persists as long as MMS is loaded (data like version-binary paths lookup)

data that could be useful:
- run your tests with `--runInBand --logHeapUsage` and report the full log
- in case you want to help more, you could try to run the debugger with exposed gc and look through there and give a report back ([see this post](https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html))

i will try it myself later and see if there is anything leaking heavily

**Comment by BioSurienDG** [comment]
I fixed it using the solution in https://github.com/nodkz/mongodb-memory-server/issues/655 (i.e. having a global setup step)

I guess initializing this in-memory database in an individual test suites has weird behaviour in jest that causes this leak

**Comment by Loki-Afro** [comment]
@hasezoey 
i suspect MMS means mongodb-memory-server ?
if jest caches the context, including the loaded modules .. this includes MMS .. you are talking about some cache, what cache exactly and can one clear it?

**Comment by hasezoey** [comment]
> i suspect MMS means mongodb-memory-server ?

yes

> if jest caches the context, including the loaded modules .. this includes MMS .. you are talking about some cache, what cache exactly and can one clear it?

like i said, i have no clue how to clear or disable it, it seems like jest just does not remove the suite contexts after use, because they are still referenced by the individual test results, or i might be completely wrong - like i said i am not proficient in debugging with the memory inspector (it was my first use of it)

**Comment by k2xl** [comment]
I'm encountering this too... Memory continues to go up (checking with logHeapUsage)
I'm wondering if there is more I need to do to fully disconnect.
```
let cached = global.db;

if (!cached) {
  cached = global.db = {
    conn: null,
    mongoMemoryServer: null,
    promise: null,
  };
}
export default async function dbConnect() {
  if (cached.conn) {
    if (mongoose.connection.readyState !== 1) {
      logger.error('Mongoose connection error');
    }

    return cached.conn;
  }

  if (!cached.promise) {
    const options: ConnectOptions = {
      connectTimeoutMS: 10000,
      heartbeatFrequencyMS: 30000,
      serverSelectionTimeoutMS: 10000,
      socketTimeoutMS: 20000,
    };

    let uri = undefined;

    if (!process.env.MONGODB_URI || process.env.NODE_ENV === 'test') {
      // create with replica
      cached.mongoMemoryServer = await MongoMemoryReplSet.create({ replSet: { count: 1 } });

      uri = cached.mongoMemoryServer.getUri();
    } else {
      uri = process.env.MONGODB_URI;
    }

    cached.promise = mongoose.connect(uri, options).then((mongoose) => {
      return mongoose;
    });
  }

  cached.conn = await cached.promise;

  if (mongoose.connection.readyState !== 1) {
    logger.error('Mongoose connection error');
  }

  return cached.conn;
}
export async function dbDisconnect() {
  if (cached.mongoMemoryServer) {
    await cached.mongoMemoryServer.stop();
    await cached.mongoMemoryServer.cleanup();
    await mongoose.disconnect();
    
  }

  if (cached.conn) {
    await cached.conn.disconnect();
    
  }
}
```

For every test I `await dbConnect()` on beforeAll and `await dbDisconnect()` on afterAll... 

`npx jest --runInBand --logHeapUsage` shows the memory usage continuously increasing... Unsure what is lingering between each test but when I ran a heap dump debug 
`node --inspect-brk --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage`

Noticed the thing that is increasing is MongoMemoryServer
