### ISSUE TITLE
Add Support for "elementaryOS 6.1"

### ISSUE THREAD

**Issue by chtpl** [nodkz/mongodb-memory-server#735]
## Versions

- Wanted System: `elementaryOS 6.1`
- Architecture: `x86_64`
- mongodb-memory-server: `8.11.2`
- node: `14.21.2`
- npm: `6.14.17`

## Detection

```sh
$ cat /etc/upstream-release/lsb-release

ID=Ubuntu
VERSION_ID=20.04
VERSION_CODENAME=focal
PRETTY_NAME="Ubuntu 20.04.5 LTS"

$ cat /etc/os-release

NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal

$ cat /usr/lib/os-release

NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal

$ cat /etc/lsb-release

DISTRIB_ID=elementary
DISTRIB_RELEASE=6.1
DISTRIB_CODENAME=jolnir
DISTRIB_DESCRIPTION="elementary OS 6 Jólnir"
```

**Comment by hasezoey** [comment]
does elementaryOS 6.1 currently not work? because elementaryOS 6 should already be handled (by either explicit or implicit upstream)

**Comment by chtpl** [comment]
unfortunately it does not work at the moment

**Comment by hasezoey** [comment]
> unfortunately it does not work at the moment

could you provide the current error?

**Comment by chtpl** [comment]
● Console

    console.warn
      Couldnt parse dist information, please report this to https://github.com/nodkz/mongodb-memory-server/issues

      at MongoBinaryDownloadUrl.getLinuxOSVersionString (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:226:15)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:168:23)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getArchiveNameLinux (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:126:38)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:93:21)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getArchiveName (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:55:38)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:55:32)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getDownloadUrl (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:30:38)
      at MongoBinaryDownload.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:169:38)
      at fulfilled (../../node_modules/tslib/tslib.js:115:62)

    console.warn
      Unknown/unsupported linux "unknown(undefined)". Falling back to legacy MongoDB build!

      at MongoBinaryDownloadUrl.getLinuxOSVersionString (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:232:13)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:168:23)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getArchiveNameLinux (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:126:38)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:93:21)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getArchiveName (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:55:38)
      at MongoBinaryDownloadUrl.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts:55:32)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at MongoBinaryDownloadUrl.getDownloadUrl (../../node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownloadUrl.js:30:38)
      at MongoBinaryDownload.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:169:38)
      at fulfilled (../../node_modules/tslib/tslib.js:115:62)

    console.warn
      Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
       Error: Status Code is 403 (MongoDB's 404)
      This means that the requested version-platform combination doesn't exist
        Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-5.0.13.tgz"
      Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
      List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive
          at ClientRequest.<anonymous> (/home/myuser/project/node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:419:17)
          at Object.onceWrapper (node:events:628:26)
          at ClientRequest.emit (node:events:513:28)
          at ClientRequest.emit (node:domain:489:12)
          at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
          at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
          at TLSSocket.socketOnData (node:_http_client:534:22)
          at TLSSocket.emit (node:events:513:28)
          at TLSSocket.emit (node:domain:489:12)
          at addChunk (node:internal/streams/readable:324:12)

      at MongoMemoryServer.<anonymous> (../../node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:295:17)
      at ../../node_modules/tslib/tslib.js:118:75
      at __awaiter (../../node_modules/tslib/tslib.js:114:16)
      at ../../node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:286:68

  ● MyController e2e › /v1/resource › POST succeeds with valid request

    Status Code is 403 (MongoDB's 404)
    This means that the requested version-platform combination doesn't exist
      Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-5.0.13.tgz"
    Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
    List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive

      at ClientRequest.<anonymous> (../../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:419:17)

**Comment by hasezoey** [comment]
thanks for this information, this means that it is actually a "bug" instead of a "distro support", will have to investigate.

just to confirm, you are running MMS in `elementaryOS`, or is it actually running inside some kind of container (docker)?

**Comment by hasezoey** [comment]
66541de422f7a720d49d681c9348005393ce8f09 should fix the underlying issue and 0e90784835f4c816e7c9b5bfbb062dc098dd1293 is something i had noticed while testing that it actually works

note: tested on `elementary/docker:fe08f970723a` (docker image) @chtpl please confirm that it actually works

this change will be in `8.11.4`, which should be available in ~10 minutes

**Comment by chtpl** [comment]
what does MMS mean? Anyways - I didn't run that in docker at that point. But after running into an the error, I used docker to run my tests inside an ubuntu container.

Thanks  for providing a fix so fast - will try it right now

**Comment by chtpl** [comment]
It works properly now :)
