### ISSUE TITLE
Bitbucket piepeline that use this package for unti tests fails after new version release

### ISSUE THREAD

**Issue by marco-bertelli** [nodkz/mongodb-memory-server#747]
## Versions

- NodeJS: 14.0.0
- mongodb-memory-server-*: 8.11.5 
- mongodb(the binary version): 0.0.0
- system: image: atlassian/default-image:2

package: mongo-memory-server 
## What is the Problem?
after this morning release i get an error on only the last uni test file (yes is not an unit test errore, because before this morning i deploy the same code)

## Debug Output

 TagService › should read a group of items
    Starting the Binary Failed (PID is undefined)! Binary: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
      at MongoInstance._launchMongod (../node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:484:13)
      at MongoInstance.<anonymous> (../node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:376:31)
      at fulfilled (../node_modules/tslib/tslib.js:164:62)

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
the provided information is not enough to see why it is happening, please provide full [Debug Log](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode) of a run

**Comment by marco-bertelli** [comment]
`2023-02-22T10:36:08.463Z MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "5.0.13"
2023-02-22T10:36:08.463Z MongoMS:DryMongoBinary generateOptions
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '/root/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'buster',
    release: '10',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary getBinaryName
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13',
  modulesCache: '/opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.13',
  relative: '/opt/atlassian/pipelines/agent/build/mongodb-binaries/mongod-x64-debian-5.0.13',
  resolveConfig: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13'
} 
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
2023-02-22T10:36:08.464Z MongoMS:DryMongoBinary locateBinary: Requested Version found in cache: "[5.0.13, /root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13]"
2023-02-22T10:36:08.464Z MongoMS:MongoBinary getPath: Mongod binary path: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
2023-02-22T10:36:08.464Z MongoMS:MongoInstance Mongo[39357]: start: Starting Processes
2023-02-22T10:36:08.464Z MongoMS:MongoInstance Mongo[39357]: _launchMongod: Launching Mongod Process
2023-02-22T10:36:08.464Z MongoMS:MongoInstance Mongo[39357]: prepareCommandArgs
2023-02-22T10:36:08.464Z MongoMS:MongoInstance Mongo[39357]: prepareCommandArgs: final argument array:["--port","39357","--dbpath","/tmp/mongo-mem--95-SsNBjd4jKjAQ","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"]
2023-02-22T10:36:08.525Z MongoMS:MongoInstance Mongo[39357]: _launchKiller: Launching Killer Process (parent: 95, child: 4882)
2023-02-22T10:36:08.608Z MongoMS:MongoInstance Mongo[39357]: stdoutHandler: ""{"t":{"$date":"2023-02-22T10:36:08.551Z"},"s":"I",  "c":"CONTROL",  "id":5324701, "ctx":"-","msg":"Test storage engine does not support enableMajorityReadConcern=true, forcibly setting to false","attr":{"storageEngine":"ephemeralForTest"}}
{"t":{"$date":"2023-02-22T10:36:08.551Z"},"s":"W",  "c":"CONTROL",  "id":4788401, "ctx":"-","msg":"Lock-free reads is not compatible with enableMajorityReadConcern=false: disabling lock-free reads."}
{"t":{"$date":"2023-02-22T10:36:08.554+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"main","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":true}}}
{"t":{"$date":"2023-02-22T10:36:08.554+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-02-22T10:36:08.554+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-02-22T10:36:08.554+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","ns":"config.tenantMigrationDonors"}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","ns":"config.tenantMigrationRecipients"}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":4882,"port":39357,"dbPath":"/tmp/mongo-mem--95-SsNBjd4jKjAQ","architecture":"64-bit","host":"29541f06-f676-46c6-afc8-91d7e517af5c-mtlm7"}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"W",  "c":"CONTROL",  "id":20720,   "ctx":"initandlisten","msg":"Memory available to mongo process is less than total system memory","attr":{"availableMemSizeMB":8192,"systemMemSizeMB":31304}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"5.0.13","gitVersion":"cfb7690563a3144d3d1175b3a20c2ec81b662a8f","openSSLVersion":"OpenSSL 1.1.1n  15 Mar 2022","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.15.0-1028-aws"}}}
{"t":{"$date":"2023-02-22T10:36:08.556+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"127.0.0.1","port":39357},"security":{"authorization":"disabled"},"storage":{"dbPath":"/tmp/mongo-mem--95-SsNBjd4jKjAQ","engine":"ephemeralForTest"}}}}
{"t":{"$date":"2023-02-22T10:36:08.557+00:00"},"s":"F",  "c":"CONTROL",  "id":6384300, "ctx":"initandlisten","msg":"Writing fatal message","attr":{"message":"terminate() called. No exception is active\n"}}""
2023-02-22T10:36:08.629Z MongoMS:MongoInstance Mongo[39357]: stdoutHandler: ""{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31380,   "ctx":"initandlisten","msg":"BACKTRACE","attr":{"bt":{"backtrace":[{"a":"55F8F3B726A5","b":"55F8EFC6B000","o":"3F076A5","s":"_ZN5mongo18stack_trace_detail12_GLOBAL__N_119printStackTraceImplERKNS1_7OptionsEPNS_14StackTraceSinkE.constprop.361","s+":"215"},{"a":"55F8F3B75129","b":"55F8EFC6B000","o":"3F0A129","s":"_ZN5mongo15printStackTraceEv","s+":"29"},{"a":"55F8F3B6DC47","b":"55F8EFC6B000","o":"3F02C47","s":"_ZN5mongo12_GLOBAL__N_111myTerminateEv","s+":"D7"},{"a":"55F8F3D013D6","b":"55F8EFC6B000","o":"40963D6","s":"_ZN10__cxxabiv111__terminateEPFvvE","s+":"6"},{"a":"55F8F3D01411","b":"55F8EFC6B000","o":"4096411","s":"_ZSt9terminatev","s+":"11"},{"a":"55F8F0C58354","b":"55F8EFC6B000","o":"FED354","s":"_ZN5mongo18PeriodicRunnerImpl15PeriodicJobImpl4_runEv.cold.543","s+":"32"},{"a":"55F8F1A4B2CC","b":"55F8EFC6B000","o":"1DE02CC","s":"_ZN5mongo18PeriodicRunnerImpl15PeriodicJobImpl5startEv","s+":"8C"},{"a":"55F8F37C94C4","b":"55F8EFC6B000","o":"3B5E4C4","s":"_ZN5mongo28CertificateExpirationMonitor5startEPNS_14ServiceContextE","s+":"244"},{"a":"55F8F11CFF76","b":"55F8EFC6B000","o":"1564F76","s":"_ZN5mongo12_GLOBAL__N_114_initAndListenEPNS_14ServiceContextEi.isra.1929","s+":"366"},{"a":"55F8F11D2A0F","b":"55F8EFC6B000","o":"1567A0F","s":"_ZN5mongo11mongod_mainEiPPc","s+":"CDF"},{"a":"55F8F106773E","b":"55F8EFC6B000","o":"13FC73E","s":"main","s+":"E"},{"a":"7F4A4BB4809B","b":"7F4A4BB24000","o":"2409B","s":"__libc_start_main","s+":"EB"},{"a":"55F8F11CCE3A","b":"55F8EFC6B000","o":"1561E3A","s":"_start","s+":"2A"}],"processInfo":{"mongodbVersion":"5.0.13","gitVersion":"cfb7690563a3144d3d1175b3a20c2ec81b662a8f","compiledModules":[],"uname":{"sysname":"Linux","release":"5.15.0-1028-aws","version":"#32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023","machine":"x86_64"},"somap":[{"b":"55F8EFC6B000","elfType":3,"buildId":"15B6BC554377D98A560F32B7C60EBDCC6FCB58CC"},{"b":"7F4A4BB24000","path":"/lib/x86_64-linux-gnu/libc.so.6","elfType":3,"buildId":"A65A82147CD98619525049D4C29CC45F88D1FB00"}]}}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F3B726A5","b":"55F8EFC6B000","o":"3F076A5","s":"_ZN5mongo18stack_trace_detail12_GLOBAL__N_119printStackTraceImplERKNS1_7OptionsEPNS_14StackTraceSinkE.constprop.361","s+":"215"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F3B75129","b":"55F8EFC6B000","o":"3F0A129","s":"_ZN5mongo15printStackTraceEv","s+":"29"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F3B6DC47","b":"55F8EFC6B000","o":"3F02C47","s":"_ZN5mongo12_GLOBAL__N_111myTerminateEv","s+":"D7"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F3D013D6","b":"55F8EFC6B000","o":"40963D6","s":"_ZN10__cxxabiv111__terminateEPFvvE","s+":"6"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F3D01411","b":"55F8EFC6B000","o":"4096411","s":"_ZSt9terminatev","s+":"11"}}}""
2023-02-22T10:36:08.629Z MongoMS:MongoInstance Mongo[39357]: stdoutHandler: ""{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F0C58354","b":"55F8EFC6B000","o":"FED354","s":"_ZN5mongo18PeriodicRunnerImpl15PeriodicJobImpl4_runEv.cold.543","s+":"32"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F1A4B2CC","b":"55F8EFC6B000","o":"1DE02CC","s":"_ZN5mongo18PeriodicRunnerImpl15PeriodicJobImpl5startEv","s+":"8C"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F37C94C4","b":"55F8EFC6B000","o":"3B5E4C4","s":"_ZN5mongo28CertificateExpirationMonitor5startEPNS_14ServiceContextE","s+":"244"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F11CFF76","b":"55F8EFC6B000","o":"1564F76","s":"_ZN5mongo12_GLOBAL__N_114_initAndListenEPNS_14ServiceContextEi.isra.1929","s+":"366"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F11D2A0F","b":"55F8EFC6B000","o":"1567A0F","s":"_ZN5mongo11mongod_mainEiPPc","s+":"CDF"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F106773E","b":"55F8EFC6B000","o":"13FC73E","s":"main","s+":"E"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"7F4A4BB4809B","b":"7F4A4BB24000","o":"2409B","s":"__libc_start_main","s+":"EB"}}}
{"t":{"$date":"2023-02-22T10:36:08.629+00:00"},"s":"I",  "c":"CONTROL",  "id":31445,   "ctx":"initandlisten","msg":"Frame","attr":{"frame":{"a":"55F8F11CCE3A","b":"55F8EFC6B000","o":"1561E3A","s":"_start","s+":"2A"}}}""
2023-02-22T10:36:08.631Z MongoMS:MongoInstance Mongo[39357]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code!
2023-02-22T10:36:08.631Z MongoMS:MongoInstance Mongo[39357]: constructor: Instance has thrown an Error: Error: Instance closed unexpectedly with code "null" and signal "SIGABRT"
2023-02-22T10:36:08.631Z MongoMS:MongoInstance Mongo[39357]: stop
2023-02-22T10:36:08.631Z MongoMS:utils Mongo[39357] killProcess: given childProcess's PID was not alive anymore
2023-02-22T10:36:08.631Z MongoMS:MongoInstance Mongo[39357]: closeHandler: code: "null", signal: "SIGABRT"
2023-02-22T10:36:08.631Z MongoMS:utils Mongo[39357] killProcess: given childProcess's PID was not alive anymore
2023-02-22T10:36:08.631Z MongoMS:MongoInstance Mongo[39357]: stop: Instance Finished Shutdown
2023-02-22T10:36:08.632Z MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance threw a Error:  UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGABRT"
    at MongoInstance.closeHandler (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:543:52)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
2023-02-22T10:36:08.632Z MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method
2023-02-22T10:36:08.632Z MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?)
2023-02-22T10:36:08.633Z MongoMS:MongoMemoryServer Mongo[41667]: stop: Called .stop() method
2023-02-22T10:36:08.633Z MongoMS:MongoMemoryServer Mongo[41667]: stop: Stopping MongoDB server on port 41667 with pid 4841`

**Comment by marco-bertelli** [comment]
here a full log in debug mode

**Comment by hasezoey** [comment]
weird, it looks like mongodb has some kind of uncatched error, maybe try to clear the binary cache and try again? 
(your cache is located at `/root/.cache/mongodb-binaries`)

**Comment by marco-bertelli** [comment]
first thanks for the help, yeah i clear the caches multiple times i think is a quite strange mongo memory error, if i rerun the pipe with the exactly same configuration but less unit tests i have no errors, in my current configuration the pipelines are hosted on bitbucket pipelines so every time i run a new one pipe the machine is "new". i tried multiple things like increase machine RAM and CPU but the result is the same, the least thing i think is a hard-disk-space problem or process limits problem but i have no options to increase those things. any type of ideas are welcome hahahah

**Comment by hasezoey** [comment]
> in my current configuration the pipelines are hosted on bitbucket pipelines so every time i run a new one pipe the machine is "new"

can you maybe post your configuration? because the provided log indicates that the binary is already downloaded (maybe downloaded via a `npm install`?)

but i dont think i will be able to help much with this problem (if the log is the same), because that looks like some mongodb internal error

**Comment by marco-bertelli** [comment]
```
2023-02-22T10:34:48.219Z MongoMS:MongoBinary getPath: "RUNTIME_DOWNLOAD" is "true", trying to download
2023-02-22T10:34:48.220Z MongoMS:MongoBinary download
2023-02-22T10:34:48.220Z MongoMS:MongoBinary download: Waiting to acquire Download lock for file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:48.221Z MongoMS:LockFile lock: Locking file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:48.221Z MongoMS:LockFile checkLock: for file "/root/.cache/mongodb-binaries/5.0.13.lock" with uuid: "undefined"
2023-02-22T10:34:48.222Z MongoMS:LockFile createLock: trying to create a lock file for "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:48.227Z MongoMS:LockFile createLock: Lock File Created for file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:48.227Z MongoMS:MongoBinary download: Download lock acquired
2023-02-22T10:34:48.227Z MongoMS:MongoBinary download: Adding version 5.0.13 to cache
2023-02-22T10:34:48.227Z MongoMS:MongoBinaryDownload getMongodPath
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary generateOptions
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '/root/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'buster',
    release: '10',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary getBinaryName
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
2023-02-22T10:34:48.227Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13',
  modulesCache: '/opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.13',
  relative: '/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server/mongodb-binaries/mongod-x64-debian-5.0.13',
  resolveConfig: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13'
} 
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary generateDownloadPath: no existing binary for version "5.0.13" was found
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary generateDownloadPath: using resolveConfig (DOWNLOAD_DIR) "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary getBinaryName
2023-02-22T10:34:48.228Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:48.228Z MongoMS:MongoBinaryDownload startDownload
2023-02-22T10:34:48.230Z MongoMS:MongoBinaryDownloadUrl Using "mongodb-linux-x86_64-debian10-5.0.13.tgz" as the Archive String
2023-02-22T10:34:48.230Z MongoMS:MongoBinaryDownloadUrl Using "https://fastdl.mongodb.org/" as the mirror
2023-02-22T10:34:48.230Z MongoMS:MongoBinaryDownload download
2023-02-22T10:34:48.230Z MongoMS:MongoBinaryDownload download: Downloading: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-5.0.13.tgz"
2023-02-22T10:34:48.231Z MongoMS:MongoBinaryDownload httpDownload
2023-02-22T10:34:48.231Z MongoMS:MongoBinaryDownload httpDownload: trying to download "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-5.0.13.tgz"
Downloading MongoDB "5.0.13": 0% (0mb / 82.5mb)
Downloading MongoDB "5.0.13": 100% (82.5mb / 82.5mb)
2023-02-22T10:34:49.034Z MongoMS:MongoBinaryDownload httpDownload: moved "/root/.cache/mongodb-binaries/mongodb-linux-x86_64-debian10-5.0.13.tgz.downloading" to "/root/.cache/mongodb-binaries/mongodb-linux-x86_64-debian10-5.0.13.tgz"
2023-02-22T10:34:49.034Z MongoMS:MongoBinaryDownload makeMD5check: Checking MD5 of downloaded binary...
2023-02-22T10:34:49.034Z MongoMS:MongoBinaryDownload makeMD5check: checkMD5 is disabled
2023-02-22T10:34:49.035Z MongoMS:MongoBinaryDownload extract
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary generateOptions
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '/root/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'debian',
    codename: 'buster',
    release: '10',
    id_like: undefined
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
}
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary getBinaryName
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:49.035Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:49.036Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13',
  modulesCache: '/opt/atlassian/pipelines/agent/build/node_modules/.cache/mongodb-memory-server/mongod-x64-debian-5.0.13',
  relative: '/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server/mongodb-binaries/mongod-x64-debian-5.0.13',
  resolveConfig: '/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13'
} 
2023-02-22T10:34:49.036Z MongoMS:DryMongoBinary generateDownloadPath: no existing binary for version "5.0.13" was found
2023-02-22T10:34:49.036Z MongoMS:DryMongoBinary generateDownloadPath: using resolveConfig (DOWNLOAD_DIR) "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
2023-02-22T10:34:49.036Z MongoMS:DryMongoBinary getBinaryName
2023-02-22T10:34:49.036Z MongoMS:DryMongoBinary combineBinaryName
2023-02-22T10:34:49.036Z MongoMS:MongoBinaryDownload extract: archive: "/root/.cache/mongodb-binaries/mongodb-linux-x86_64-debian10-5.0.13.tgz" final: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
2023-02-22T10:34:49.037Z MongoMS:MongoBinaryDownload extractTarGz
2023-02-22T10:34:52.204Z MongoMS:MongoBinary download: Removing Download lock
2023-02-22T10:34:52.204Z MongoMS:LockFile unlock: Unlocking file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:52.204Z MongoMS:LockFile checkLock: for file "/root/.cache/mongodb-binaries/5.0.13.lock" with uuid: "37701b8b-3f7f-4637-b9d6-6e55be908253"
2023-02-22T10:34:52.205Z MongoMS:LockFile checkLock: Lock File Already exists, and is for *this* process, with uuid: "37701b8b-3f7f-4637-b9d6-6e55be908253"
2023-02-22T10:34:52.205Z MongoMS:LockFile unlock: Lock Status was "availableInstance" for file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:52.205Z MongoMS:LockFile unlockCleanup: for file "/root/.cache/mongodb-binaries/5.0.13.lock"
2023-02-22T10:34:52.208Z MongoMS:MongoBinary download: Download lock removed
2023-02-22T10:34:52.208Z MongoMS:MongoBinary getPath: Mongod binary path: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
Mongodb-Memory-Server* found binary: "/root/.cache/mongodb-binaries/mongod-x64-debian-5.0.13"
npm WARN The package @types/multer is included as both a dev and production dependency.
npm WARN The package dotenv is included as both a dev and production dependency.
npm WARN The package mongodb-memory-server is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
added 1271 packages from 862 contributors and audited 1283 packages in 62.244s
108 packages are looking for funding
  run `npm fund` for details
found 28 vulnerabilities (9 moderate, 16 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by marco-bertelli** [comment]
npm install logs

**Comment by hasezoey** [comment]
i dont see anything wrong in the download logs.

i cant really help with this problem, though here are some things to try:
- try to use a higher version, like 6.0.4
- try to use a 4.x version, like 4.4.17 (because 5.0 and up require AVX)
- try to use a different base image if possible then debian 10

**Comment by marco-bertelli** [comment]
thanks tomorrow i will try your hints!
