### ISSUE TITLE
Cannot change mongo version

### ISSUE THREAD

**Issue by FloUz-ai** [nodkz/mongodb-memory-server#749]
- NodeJS: 16.18.1
- mongodb-memory-server-*: 8.11.5 
- mongodb(the binary version): 0
- mongoose: 0.0.0 
- system:  MAC OS

package: mongo-memory-server 

## What is the Problem?

What ever the version I change, I always have the same error : 

```
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
     Error: Status Code is 403 (MongoDB's 404)
    This means that the requested version-platform combination doesn't exist
      Used Url: "https://fastdl.mongodb.org/osx/mongodb-macos-arm64-v6.0.2.tgz"
    Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
    List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive
```

I set the version I want in the package.json as follow :

```
"config": {
    "mongodbMemoryServer": {
      "version": "v6.0.2",
      "debug": "1"
    }
  }
```

Any idea why I cannot change my version

**Comment by hasezoey** [comment]
>       Used Url: "https://fastdl.mongodb.org/osx/mongodb-macos-arm64-v6.0.2.tgz"
>       "version": "v6.0.2",

try the version without the prefix `v`, see [Mongodb Community Downloads Archive](https://www.mongodb.com/download-center/community/releases/archive) for available archives and their names

**Comment by FloUz-ai** [comment]
I try, and now I have this error: 

```
 Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
     UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGKILL"
```

**Comment by hasezoey** [comment]
> I try, and now I have this error:
>      UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGKILL"

now it looks like the same error as in https://github.com/nodkz/mongodb-memory-server/issues/741, could you provide the [debug log](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)?

**Comment by FloUz-ai** [comment]
Sure here what I have 

```
MongoMS:ResolveConfig Debug Mode Enabled, through package.json +0ms
  MongoMS:MongoMemoryServer create: Called .create() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions: forceSamePort: false +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
  instance: {
    port: 50747,
    dbName: '',
    ip: '127.0.0.1',
    storageEngine: 'ephemeralForTest',
    replSet: undefined,
    dbPath: '/var/folders/cw/vmfn_7l104d_x2ntc_gn22p80000gn/T/mongo-mem--43278-rPEUJ9jpeqeI',
    tmpDir: {
      name: '/var/folders/cw/vmfn_7l104d_x2ntc_gn22p80000gn/T/mongo-mem--43278-rPEUJ9jpeqeI',
      removeCallback: [Function: _cleanupCallback]
    },
    keyfileLocation: undefined,
    launchTimeout: undefined,
    args: undefined,
    auth: false
  },
  binary: undefined,
  spawn: undefined
} +2ms
  MongoMS:MongoInstance create: Called .create() method +0ms
  MongoMS:MongoInstance Mongo[50747]: start +0ms
  MongoMS:MongoBinary getPath +0ms
  MongoMS:DryMongoBinary generateOptions +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +0ms
  MongoMS:DryMongoBinary generatePaths {
  version: '6.0.2',
  downloadDir: '',
  os: { os: 'darwin' },
  platform: 'darwin',
  arch: 'arm64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +1ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  modulesCache: '/Users/***/Documents/Repo/Repoback/node_modules/.cache/mongodb-memory-server/mongod-arm64-darwin-6.0.2',
  relative: '/Users/***/Documents/Repo/Repoback/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  resolveConfig: ''
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in legacyHomeCache: "/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2" +0ms
  MongoMS:MongoBinary getPath: MongoBinary options: {
  "version": "6.0.2",
  "downloadDir": "/Users/***/.cache/mongodb-binaries",
  "os": {
    "os": "darwin"
  },
  "platform": "darwin",
  "arch": "arm64",
  "systemBinary": "",
  "checkMD5": false
} +2ms
  MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "6.0.2" +1ms
  MongoMS:DryMongoBinary generateOptions +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +0ms
  MongoMS:DryMongoBinary generatePaths {
  version: '6.0.2',
  downloadDir: '/Users/***/.cache/mongodb-binaries',
  os: { os: 'darwin' },
  platform: 'darwin',
  arch: 'arm64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  modulesCache: '/Users/***/Documents/Repo/Repoback/node_modules/.cache/mongodb-memory-server/mongod-arm64-darwin-6.0.2',
  relative: '/Users/***/Documents/Repo/Repoback/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  resolveConfig: '/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2'
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2" +0ms
  MongoMS:DryMongoBinary locateBinary: running generateDownloadPath +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +0ms
  MongoMS:DryMongoBinary generatePaths {
  version: '6.0.2',
  downloadDir: '/Users/***/.cache/mongodb-binaries',
  os: { os: 'darwin' },
  platform: 'darwin',
  arch: 'arm64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +1ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  modulesCache: '/Users/***/Documents/Repo/Repoback/node_modules/.cache/mongodb-memory-server/mongod-arm64-darwin-6.0.2',
  relative: '/Users/***/Documents/Repo/Repoback/mongodb-binaries/mongod-arm64-darwin-6.0.2',
  resolveConfig: '/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2'
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2" +1ms
  MongoMS:DryMongoBinary locateBinary: found binary at "/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2" +1ms
  MongoMS:MongoBinary getPath: Mongod binary path: "/Users/***/.cache/mongodb-binaries/mongod-arm64-darwin-6.0.2" +3ms
  MongoMS:MongoInstance Mongo[50747]: start: Starting Processes +5ms
  MongoMS:MongoInstance Mongo[50747]: _launchMongod: Launching Mongod Process +0ms
  MongoMS:MongoInstance Mongo[50747]: prepareCommandArgs +0ms
  MongoMS:MongoInstance Mongo[50747]: prepareCommandArgs: final argument array:["--port","50747","--dbpath","/var/folders/cw/vmfn_7l104d_x2ntc_gn22p80000gn/T/mongo-mem--43278-rPEUJ9jpeqeI","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"] +0ms
  MongoMS:MongoInstance Mongo[50747]: _launchKiller: Launching Killer Process (parent: 43278, child: 43299) +7ms
  MongoMS:MongoInstance Mongo[50747]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code! +3ms
  MongoMS:MongoInstance Mongo[50747]: constructor: Instance has thrown an Error: Error: Instance closed unexpectedly with code "null" and signal "SIGKILL" +1ms
  MongoMS:MongoInstance Mongo[50747]: stop +0ms
  MongoMS:utils Mongo[50747] killProcess: given childProcess's PID was not alive anymore +0ms
  MongoMS:MongoInstance Mongo[50747]: closeHandler: code: "null", signal: "SIGKILL" +0ms
  MongoMS:utils Mongo[50747] killProcess: killerProcess: sending "SIGINT" +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance threw a Error:  UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGKILL"
    at MongoInstance.closeHandler (/Users/***/Documents/Repo/Repo/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:543:52)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) +17ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method +8ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?) +0ms
  MongoMS:utils Mongo[50747] killProcess: killerProcess: got exit signal, Code: null, Signal: SIGINT +26ms
  MongoMS:MongoInstance Mongo[50747]: stop: Instance Finished Shutdown +26ms
```

**Comment by hasezoey** [comment]
>   MongoMS:MongoInstance Mongo[50747]: prepareCommandArgs: final argument array:["--port","50747","--dbpath","/var/folders/cw/vmfn_7l104d_x2ntc_gn22p80000gn/T/mongo-mem--43278-rPEUJ9jpeqeI","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"] +0ms
>   MongoMS:MongoInstance Mongo[50747]: _launchKiller: Launching Killer Process (parent: 43278, child: 43299) +7ms
>   MongoMS:MongoInstance Mongo[50747]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code! +3ms

as can be seen in those lines, the binary is somehow prevented from being spawned (instantly killed), the same issue as in https://github.com/nodkz/mongodb-memory-server/issues/741, i cannot help with that because i dont have a mac and have not found any issues by searching on what would cause this, you would have to investigate yourself (thing like some enhanced security? or somehow the node process is prevented from spawning the binary?
things you could try:
- check if the binary has the execute permissions (it should have by default, but could also need to be checked)
- remove all binaries and let it be re-downloaded
- try a earlier version of a binary (as suggested in the mentioned issue `5.0.14` may work)
- try to factory-reset the mac and see if that works (would not personally recommend this)

**Comment by FloUz-ai** [comment]
I tried th step, but nothing. I guess I can close it
