### ISSUE TITLE
problem with docker image node:16.14.0/(macos m1) 

### ISSUE THREAD

**Issue by Rob-94** [nodkz/mongodb-memory-server#752]
- NodeJS: 16.14.0
- mongodb-memory-server-*:"^8.12.0"
- mongoose: 6.2.9
- system: MacOs m1 (Docker desktop)
package: mongo-memory-server 

on Mac m1 with Docker desktop, using node:16.14.0 image, after  building image and running the container when jest runs the  test getting this error 

```txt
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
Error: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
 Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-aarch64-debian10-5.0.13.tgz"
 Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
 List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive
 at ClientRequest.<anonymous> (/usr/app/node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:419:17)
  at Object.onceWrapper (node:events:640:26)
  at ClientRequest.emit (node:events:520:28)
  at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
  at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
  at TLSSocket.socketOnData (node:_http_client:482:22)
  at TLSSocket.emit (node:events:520:28)
  at addChunk (node:internal/streams/readable:315:12)
  at readableAddChunk (node:internal/streams/readable:289:9)
  at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
```
 
----------Dockerfile------------------------

```docker
FROM --platform=linux/amd64 node:16.14.0
WORKDIR /usr/app
COPY ./package.json ./
RUN npm i
COPY ./ ./
CMD ["npm", "run","test:watch", "src/api/audioFiles/audioFileRoutes/audioFileControllers/sendAudio/index.test.js"]
```

--------------------------------------------

**Comment by hasezoey** [comment]
> Error: Status Code is 403 (MongoDB's 404)
> This means that the requested version-platform combination doesn't exist

as the error says, there is no binary for `mongodb-linux-aarch64-debian10-5.0.13.tgz`, normally you would need to find a version that supports aarch64 for your distro and overwrite the version, but debian does not have any aarch64 binaries, so you could try to use binaries from ubuntu.

Config Option [`ARCHIVE_NAME`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#archive_name) will be used to set this (there is currently no option to overwrite the distro byitself)

i would recommend to set the version in the dockerfile, otherwise it will also apply to any non-docker environment

Example:
```dockerfile
# put this environment option before the binary is downloaded and run (before install and CMD)
ENV MONGOMS_ARCHIVE_NAME="mongodb-linux-aarch64-ubuntu2004-5.0.13.tgz"
RUN npm i
```
(replace `ubuntu2004` with any other ubuntu version, if the current one does not work, like `ubuntu2204` or `ubuntu1804`)

**Comment by carnytom** [comment]
Similar error and when I go to the URL directly, looks like it's blocked now.. 


  Used Url: "https://fastdl.mongodb.org/osx/mongodb-osx-ssl-arm64-4.0.14.tgz"
Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
List of available versions can be found here:
  https://www.mongodb.org/dl/linux for Linux
  https://www.mongodb.org/dl/osx for OSX
  https://www.mongodb.org/dl/win32 for Windows
    at ClientRequest.<anonymous> (/Users/thartsgrove/upwise/mlf_cfl_control_tower/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:386:44)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)

**Comment by hasezoey** [comment]
>  looks like it's blocked now..

mongodb's 403 (access denied) is basically 404, it never existed in the first place

> Used Url: "https://fastdl.mongodb.org/osx/mongodb-osx-ssl-arm64-4.0.14.tgz"

macos arm build only exist since version 6.0.0, before it has to use x86_64 via rosetta translation (but note that rosetta may not properly support AVX, which mongodb since 5.0 requires for x86_64)

**Comment by carnytom** [comment]
but updating the version to 6.0.0 r higher As [hasezoey](https://github.com/hasezoey) mentioned
