### ISSUE TITLE
Unit tests on heroku don't work

### ISSUE THREAD

**Issue by Suiken** [nodkz/mongodb-memory-server#763]
## Versions

- NodeJS: 19.1.0
- NPM: 9.2.0
- mongodb-memory-server-*: 8.12.2
- mongodb(the binary version): 5.0.13 (also tried 4.4.8)
- mongodb(the js package): 4.13.0
- mongoose: 6.6.1
- system: Heroku stack-20 (Ubuntu 20.04.6 LTS)

package: mongo-memory-server

## What is your question?

Hi,

I tried set pipelines on heroku run the unit tests but it didn't work.
These tests actually work on my local environment (MacOS 13.2.1).
I am creating a simple MongoMemoryServer : `await MongoMemoryServer.create();`
I first had a problem with a libcrypto.so.1.1 file that was not found, I fixed by lowering down the version of the Heroku stack from 22 to 20 (which is also the version of Ubuntu).

Here are the logs from Heroku:
`console.log
      Downloading MongoDB "5.0.13": 0% (0mb / 82.5mb)
      at MongoBinaryDownload.printDownloadProgress (../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:512:15)
    console.log
      Downloading MongoDB "5.0.13": 56.2% (46.4mb / 82.5mb)
      at MongoBinaryDownload.printDownloadProgress (../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:512:15)
    console.log
      Downloading MongoDB "5.0.13": 100% (82.5mb / 82.5mb)
      at MongoBinaryDownload.printDownloadProgress (../node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:512:15)`

`thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."`

The timeout is because since the MongoMemoryServer is not created, it gets stuck.

Does someone had that kind of problem ? If yes could you fix it ?

Thank you !

**Comment by hasezoey** [comment]
[please use triple back-quotes for multi-line code blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

---

does the test get killed because of the timeout before it can finish the download or is it some time after the download?

if this is the case, please provide [Debug logs](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)

---

it is recommended to run the download with not a small timeout, for example run it in a jest `globalSetup` or a mocha `mochaGlobalSetup` or if wanted in a entirely own process (not documented)

see [Integration with Test Runners](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners)

>  I first had a problem with a libcrypto.so.1.1 file that was not found, I fixed by lowering down the version of the Heroku stack from 22 to 20 (which is also the version of Ubuntu).

you could also update the used mongodb version to `6.0.4` or higher, which has build binaries for ubuntu 2204

**Comment by Suiken** [comment]
I indeed didn't use the globalSetup to create a new database for each file but I have now modified it and it all works.

Just need to run in band to not get any conflicts on the database but I guess I can't do anything about it.

The 6.0.4 also works for ubuntu 2204.

Thank you !

**Comment by Suiken** [comment]
Thank you for pointing it out, I was actually doing that ... Thank's a lot it now works ! ✊
