### ISSUE TITLE
Add URL to download error

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#768]
Currently errors in MongoBinaryDownload's `httpDownload` do not list the URL without the debug log on, for example:

```txt
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
 Error: Response header "content-length" is empty!
    at HttpsClientRequest.<anonymous> (file:///home/runner/work/mongoose/mongoose/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:332:32)
    at Object.onceWrapper (ext:deno_node/_stream.mjs:1929:30)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1852:9)
```

which would require re-running with debug logs enabled, even though it could be tested if the url is even correct if added to the error

(this issue is about all errors from `httpDownload`, not just content-length)

**Comment by hasezoey** [comment]
added with 88a7cce7dfff71e471c9fe00b7807a15c09e22e0, released with [v8.13.0](https://github.com/nodkz/mongodb-memory-server/releases/tag/v8.13.0)
