### ISSUE TITLE
(Windows) Unable to Start MongoInstance: spawn UNKNOWN

### ISSUE THREAD

**Issue by developerwithout** [nodkz/mongodb-memory-server#769]
## Versions

- NodeJS: v18.15.0
- mongodb-memory-server-*: 8.12.2
- mongodb(the binary version): 0.0.0 
- mongoose: 7.2.1 
- system: Windows

package: mongo-memory-server

## What is the Problem?

Unable to start and run successfully a mongodb-memory-server instance.

## Code Example

```js
beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    await mongoServer.start();
    const mongoUri = mongoServer.getUri();
    await mongoose.connect(mongoUri, { useNewUrlParser: true, useUnifiedTopology: true });
    mongooseMock(mongoose);
  });

  afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
  });
```

## Debug Output

<details>
<summary>Debug Output</summary>

```log
2023-06-06T20:54:59.043Z MongoMS:ResolveConfig Debug Mode Enabled, through Environment Variable
2023-06-06T20:54:59.105Z MongoMS:ResolveConfig findPackageJson: Found package.json at "C:\Users\user\Projects\Personal\Blog\server\package.json"
2023-06-06T20:54:59.134Z MongoMS:ResolveConfig findPackageJson: Found package with non-empty config field at "C:\Users\user\Projects\Personal\Blog\server\package.json"
2023-06-06T20:54:59.134Z MongoMS:ResolveConfig processConfigOption { debug: 'true' } C:\Users\user\Projects\Personal\Blog\server
2023-06-06T20:55:13.271Z MongoMS:MongoMemoryServer create: Called .create() method
2023-06-06T20:55:13.280Z MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method
2023-06-06T20:55:13.282Z MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method
2023-06-06T20:55:13.282Z MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions: forceSamePort: false
2023-06-06T20:55:13.354Z MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
  instance: {
    port: 52433,
    dbName: '',
    ip: '127.0.0.1',
    storageEngine: 'ephemeralForTest',
    replSet: undefined,
    dbPath: 'C:\\Users\\user\\AppData\\Local\\Temp\\mongo-mem-lDJdRa',
    tmpDir: 'C:\\Users\\user\\AppData\\Local\\Temp\\mongo-mem-lDJdRa',
    keyfileLocation: undefined,
    launchTimeout: undefined,
    args: undefined,
    auth: false
  },
  binary: undefined,
  spawn: undefined
}
2023-06-06T20:55:13.368Z MongoMS:MongoInstance create: Called .create() method
2023-06-06T20:55:13.368Z MongoMS:MongoInstance Mongo[52433]: start
2023-06-06T20:55:13.369Z MongoMS:MongoBinary getPath
2023-06-06T20:55:13.370Z MongoMS:DryMongoBinary generateOptions
2023-06-06T20:55:13.371Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-06-06T20:55:13.371Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '',
  os: { os: 'win32' },
  platform: 'win32',
  arch: 'x64',
  systemBinary: ''
}
2023-06-06T20:55:13.380Z MongoMS:DryMongoBinary getBinaryName
2023-06-06T20:55:13.382Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.383Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.383Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.383Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: 'C:\\Users\\user\\.cache\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  modulesCache: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-5.0.13.exe',
  relative: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  resolveConfig: ''
}
2023-06-06T20:55:13.467Z MongoMS:DryMongoBinary generateDownloadPath: Found binary in legacyHomeCache: "C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe"
2023-06-06T20:55:13.468Z MongoMS:MongoBinary getPath: MongoBinary options: {
  "version": "5.0.13",
  "downloadDir": "C:\\Users\\user\\.cache\\mongodb-binaries",
  "os": {
    "os": "win32"
  },
  "platform": "win32",
  "arch": "x64",
  "systemBinary": "",
  "checkMD5": false
}
2023-06-06T20:55:13.468Z MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "5.0.13"
2023-06-06T20:55:13.468Z MongoMS:DryMongoBinary generateOptions
2023-06-06T20:55:13.469Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-06-06T20:55:13.469Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: 'C:\\Users\\user\\.cache\\mongodb-binaries',
  os: { os: 'win32' },
  platform: 'win32',
  arch: 'x64',
  systemBinary: ''
}
2023-06-06T20:55:13.469Z MongoMS:DryMongoBinary getBinaryName
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.470Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: 'C:\\Users\\user\\.cache\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  modulesCache: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-5.0.13.exe',
  relative: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  resolveConfig: 'C:\\Users\\user\\.cache\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe'
}
2023-06-06T20:55:13.476Z MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe"
2023-06-06T20:55:13.477Z MongoMS:DryMongoBinary locateBinary: running generateDownloadPath
2023-06-06T20:55:13.477Z MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true"
2023-06-06T20:55:13.477Z MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: 'C:\\Users\\user\\.cache\\mongodb-binaries',
  os: { os: 'win32' },
  platform: 'win32',
  arch: 'x64',
  systemBinary: ''
}
2023-06-06T20:55:13.477Z MongoMS:DryMongoBinary getBinaryName
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary combineBinaryName
2023-06-06T20:55:13.478Z MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: 'C:\\Users\\user\\.cache\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  modulesCache: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\node_modules\\.cache\\mongodb-memory-server\\mongod-x64-win32-5.0.13.exe',
  relative: 'C:\\Users\\user\\Projects\\Personal\\Blog\\server\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe',
  resolveConfig: 'C:\\Users\\user\\.cache\\mongodb-binaries\\mongod-x64-win32-5.0.13.exe'
}
2023-06-06T20:55:13.479Z MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe"
2023-06-06T20:55:13.479Z MongoMS:DryMongoBinary locateBinary: found binary at "C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe"
2023-06-06T20:55:13.480Z MongoMS:MongoBinary getPath: Mongod binary path: "C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe"
2023-06-06T20:55:13.481Z MongoMS:MongoInstance Mongo[52433]: start: Starting Processes
2023-06-06T20:55:13.482Z MongoMS:MongoInstance Mongo[52433]: _launchMongod: Launching Mongod Process
2023-06-06T20:55:13.483Z MongoMS:MongoInstance Mongo[52433]: prepareCommandArgs
2023-06-06T20:55:13.483Z MongoMS:MongoInstance Mongo[52433]: prepareCommandArgs: final argument array:["--port","52433","--dbpath","C:\\Users\\user\\AppData\\Local\\Temp\\mongo-mem-lDJdRa","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"]
2023-06-06T20:55:15.433Z MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance threw a Error:  Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at MongoInstance._launchMongod (C:\Users\user\Projects\Personal\Blog\server\node_modules\mongodb-memory-server-core\src\util\MongoInstance.ts:474:31)
    at MongoInstance.<anonymous> (C:\Users\user\Projects\Personal\Blog\server\node_modules\mongodb-memory-server-core\src\util\MongoInstance.ts:376:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\Projects\Personal\Blog\server\node_modules\tslib\tslib.js:164:62) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
2023-06-06T20:55:15.447Z MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method
2023-06-06T20:55:15.447Z MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?)
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
i dont know why the spawning fails, could you try to remove file `C:\Users\user\.cache\mongodb-binaries\mongod-x64-win32-5.0.13.exe` and re-download it and see if that fixes it?
