### ISSUE TITLE
 A systemerror occurs when starting mongode-memory-server.

### ISSUE THREAD

**Issue by akasataikisiti** [nodkz/mongodb-memory-server#770]
## Versions

- OS: macOS 13.4 22F66 arm64
- MongoDB Memory Server version: 8.13.0
- Mongoose version: 7.2.2
- Node.js version: 18.13.0
- jest: ^29.5.0

## What is the Problem?

System error when trying to run tests using mongode-memory-server.

## Code Example

```ts
import { MongoMemoryServer } from "mongodb-memory-server";
import mongoose from "mongoose";
import { app } from "../app";

let mongo: any;

beforeAll(async () => {
  const mongo = await MongoMemoryServer.create();
  const mongoUri = mongo.getUri();

  await mongoose.connect(mongoUri, {});
});

beforeEach(async () => {
  const collections = await mongoose.connection.db.collections();

  for (let collection of collections) {
    await collection.deleteMany({});
  }
});

afterAll(async () => {
  if (mongo) {
    await mongo.stop();
  }
  await mongoose.connection.close();
});

```

## Debug Output

```txt
console.warn
  Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
   Error: spawn Unknown system error -86
      at ChildProcess.spawn (node:internal/child_process:413:11)
      at spawn (node:child_process:757:9)
      at MongoInstance._launchMongod (/Users/mac_a/work/for_Learn/ticketing/auth/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:474:31)
      at MongoInstance.<anonymous> (/Users/mac_a/work/for_Learn/ticketing/auth/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:376:31)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/mac_a/work/for_Learn/ticketing/auth/node_modules/tslib/tslib.js:164:62) {
    errno: -86,
    code: 'Unknown system error -86',
    syscall: 'spawn'
  }

    at MongoMemoryServer.<anonymous> (node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:293:17)
    at node_modules/tslib/tslib.js:167:75
    at __awaiter (node_modules/tslib/tslib.js:163:16)
    at node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:284:68
```

## Do you know *why* it happenes?

*no*

## Additional Information

I Read the past issue, and  run the command `export MONGOMS_ARCH=x64` in the terminal
and then running the test. But didn't work either.

Thank you.

**Comment by akasataikisiti** [comment]
Thank you for your reply.
I solved the problem by specifying the mongodb download url.

I was able to successfully run the test by running the following command in the terminal. 
`export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/osx/mongodb-macos-arm64-6.0.5.tgz`
