### ISSUE TITLE
Incorrect md5 on CircleCI

### ISSUE THREAD

**Issue by smeijer** [nodkz/mongodb-memory-server#85]
NPM install is crashing due to incorrect MD5.

```
mongodb-memory-server: checking MongoDB binaries cache...
Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-latest.tgz
Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-latest.tgz.md5
(node:2047) UnhandledPromiseRejectionWarning: Error: MongoBinaryDownload: md5 check is failed
    at MongoBinaryDownload._callee3$ (/home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:217:23)
    at tryCatch (/home/circleci/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/circleci/app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/circleci/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:52:191)
    at /home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:52:437
    at new Promise (<anonymous>)
    at MongoBinaryDownload.<anonymous> (/home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:52:99)
    at MongoBinaryDownload.checkMd5 (/home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:228:22)
    at MongoBinaryDownload._callee2$ (/home/circleci/app/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:179:29)
(node:2047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by smeijer** [comment]
Okay, perhaps it has to do with the fact that I don't have access to the download urls. Not to the `tgz`, nor to the `md5`.

```xml
<Error>
  <link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
  <style type="text/css" id="dark-mode-custom-style"/>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>9FB1823C4E56EA91</RequestId>
  <HostId>
    j2abc...uMCMw=
  </HostId>
</Error>
```

**Comment by smeijer** [comment]
More info:

I think it's because there is no release for my `debian version`.

```
// getos()
{ 
  "os": "linux",
  "dist":"Debian",
  "release":"unstable",
  "codename":"sid"
}
```

https://github.com/nodkz/mongodb-memory-server/blob/5911cdc4a3da2fb70ee54a85294e6548d10c97fd/src/util/MongoBinaryDownloadUrl.js#L117-L128
